Repository entando/app-builder, pull requests merged in 2020-05, with the labels that each got.

#704 ENG-424 clear auth info during logout
  src/app-init/apiManager.js
Labels: size/XS

#706 ENG-423 fix on persisting state of current user auth
  src/state/store.js
Labels: approved, size/XS

#708 ENG-441 Fix ecr component usage message logic
  src/ui/component-repository/components/common/ConfirmUninstallModal.js
  test/test/mocks/component-repository/components.js
Labels: approved, size/XS

#707 ENG-494 implement loaders for page actions
  src/state/pages/actions.js
  test/state/pages/actions.test.js
Labels: size/M

#705 ENG-425 fetch current user auth when login done
  src/api/currentUserAuth.js
  src/state/current-user-auth/actions.js
  src/state/login-form/actions.js
  test/test/mocks/currentUserAuth.js
Labels: approved, size/M

#709 ENG-519 implement app-builder side for expand/collapse all
  package-lock.json
  package.json
  sass/pages/common/PageTree.scss
  sass/pages/config/ContentPages.scss
  src/state/pages/actions.js
  src/state/pages/reducer.js
  src/state/pages/types.js
  src/ui/pages/common/PageTree.js
  src/ui/pages/common/PageTreeContainer.js
  src/ui/pages/common/PageTreeSelectorContainer.js
  src/ui/pages/config/ContentPages.js
  src/ui/pages/config/ContentPagesContainer.js
  test/state/pages/actions.test.js
  test/state/pages/reducer.test.js
  test/ui/pages/common/PageTreeSelectorContainer.test.js
  test/ui/pages/config/ContentPageContainer.test.js
Labels: approved, do-not-merge/work-in-progress, size/L

#710 ENG-580 Roles form UX specs + current user auth reducer change
  src/api/currentUserAuth.js
  src/api/permissions.js
  src/app-init/apiManager.js
  src/state/current-user-auth/actions.js
  src/state/current-user-auth/reducer.js
  src/state/current-user-auth/selectors.js
  src/state/current-user-auth/types.js
  src/state/login-form/actions.js
  src/state/permissions/actions.js
  src/state/permissions/const.js
  src/state/permissions/reducer.js
  src/state/permissions/selectors.js
  src/state/permissions/types.js
  src/state/rootReducer.js
  src/state/store.js
  src/ui/common/form/SwitchRenderer.js
  src/ui/roles/add/AddFormContainer.js
  src/ui/roles/common/PermissionGrid.js
  src/ui/roles/common/RoleForm.js
  src/ui/roles/edit/EditFormContainer.js
  test/state/current-user-auth/actions.test.js
  test/state/current-user-auth/reducer.test.js
  test/state/current-user-auth/selectors.test.js
  test/state/permissions/actions.test.js
  test/state/permissions/reducer.test.js
  test/state/permissions/selectors.test.js
  test/test/mocks/currentUserAuth.js
  test/test/mocks/loggedUserPermissions.js
  test/test/mocks/permissions.js
Labels: approved, size/L

#711 ENG-579 restrict admin area access if no permissions
  package-lock.json
  package.json
  src/api/permissions.js
  src/auth/keycloak/KeycloakProviderContainer.js
  src/state/permissions/actions.js
  src/state/permissions/const.js
  src/ui/auth/withPermissions.js
  src/ui/dashboard/DashboardPage.js
  test/ui/dashboard/DashboardPage.test.js
Labels: approved, size/L

#714 ENG-582 hide cms menu items if not enough permissions in app-builder
  package.json
  src/state/permissions/const.js
  src/ui/auth/withPermissions.js
  src/ui/internal-page/BrandMenuContainer.js
  src/ui/internal-page/InternalPage.js
Labels: approved, size/XL

#713 ENG-583 action enabling depending on user permissions
  __mocks__/@entando/utils.js
  src/ui/auth/withPermissions.js
  src/ui/dashboard/DashboardPage.js
  src/ui/dashboard/UserManagement.js
  src/ui/dashboard/UserManagementContainer.js
  src/ui/dashboard/UxPatterns.js
  src/ui/dashboard/UxPatternsContainer.js
  src/ui/users/list/UserListMenuActions.js
  src/ui/users/list/UserListPage.js
  src/ui/users/list/UserListTableContainer.js
  src/ui/widgets/list/WidgetListRow.js
  src/ui/widgets/list/WidgetListTable.js
  test/ui/dashboard/DashboardPage.test.js
  test/ui/dashboard/UserManagement.test.js
  test/ui/dashboard/UserManagementContainer.test.js
  test/ui/users/list/ListDataTypePage.test.js
  test/ui/users/list/UserListMenuActions.test.js
  test/ui/widgets/list/WidgetListTable.test.js
Labels: approved, size/L
