Repository entando/app-builder, pull requests merged in 2020-07, with the labels that each got.

#743 JX build trigger - CMS 0.2.96
  src/ui/internal-page/BrandMenuContainer.js
Labels: approved, size/XS

#744 ENG-640 dependency update for entando frontend libaries
  package-lock.json
  package.json
Labels: approved, size/M

#742 ENG-789 updated component repository labels
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
Labels: approved, size/S

#745 ENG-820 updated package
  package-lock.json
  package.json
Labels: approved, size/XS

#746 ENG-725 implement category details references page
  sass/categories/detail/DetailCategoryTable.scss
  src/api/categories.js
  src/app-init/router.js
  src/locales/en.js
  src/locales/it.js
  src/state/categories/actions.js
  src/ui/categories/detail/DetailCategoryTable.js
  src/ui/categories/detail/DetailCategoryTableContainer.js
  src/ui/common/references/GenericRefsTable.js
  src/ui/groups/detail/GroupDetailTabUsers.js
  test/api/categories.test.js
  test/state/categories/actions.test.js
  test/ui/categories/detail/DetailCategoryTable.test.js
  test/ui/categories/detail/DetailCategoryTableContainer.test.js
  test/ui/common/references/GenericRefsTable.test.js
Labels: approved, size/L

#747 temporarily use apimanager 6.5 to prevent a regression with urls
  package.json
Labels: approved, size/XS

#748 Set specific apiManager version
  package.json
Labels: approved, size/XS

#749 ENG-643 Align Error Pages
  package-lock.json
  package.json
  src/ui/app/App.js
  src/ui/app/PageNotFound.js
  src/ui/app/PageNotFoundContainer.js
  test/ui/app/App.test.js
Labels: approved, size/M

#750 updated api-manager package
  package-lock.json
  package.json
Labels: approved, size/XS

#751 ENG-789 update plugins label
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
Labels: approved, size/XS

#752 ENG-463 implement new logic for expired account and password
  sass/patternfly.scss
  sass/users/common/UserStatus.scss
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/users/list/UserListTable.js
  test/test/mocks/users.js
  test/ui/users/list/UserListTable.test.js
Labels: size/L

#741 ENG-815 added version select when provided
  src/models/component-repository/components.js
  src/state/component-repository/components/actions.js
  src/ui/component-repository/components/common/ComponentInstallActions.js
  src/ui/component-repository/components/item/ComponentImage.js
  src/ui/component-repository/components/item/install-controls/ComponentInstallActions.js
  src/ui/component-repository/components/item/install-controls/ComponentInstallActionsContainer.js
  src/ui/component-repository/components/item/install-controls/ConfirmUninstallModal.js
  src/ui/component-repository/components/item/install-controls/FailedInstallState.js
  src/ui/component-repository/components/item/install-controls/InProgressInstallState.js
  src/ui/component-repository/components/item/install-controls/InstallButton.js
  src/ui/component-repository/components/item/install-controls/UninstallButton.js
  src/ui/component-repository/components/list/ComponentListGridView.js
  src/ui/component-repository/components/list/ComponentListListView.js
  src/ui/component-repository/components/list/ComponentListPage.js
  src/ui/component-repository/components/list/ComponentListViewModeSwitcherContainer.js
  test/ui/component-repository/components/item/ComponentImage.test.js
  test/ui/component-repository/components/item/install-controls/ComponentInstallActions.test.js
  test/ui/component-repository/components/item/install-controls/ComponentInstallActionsContainer.test.js
  test/ui/component-repository/components/list/ComponentListGridView.test.js
  test/ui/component-repository/components/list/ComponentListListView.test.js
  test/ui/component-repository/components/list/ComponentListViewModeSwitcherContainer.test.js
Labels: approved, size/L

#753 ENG-686 add status card for contents on dashboard
  src/ui/dashboard/DashboardPage.js
  src/ui/file-browser/utils/downloadFile.js
Labels: approved, size/M

#754 ENG-811 hide data menu items
  src/ui/internal-page/BrandMenuContainer.js
Labels: approved, size/S

#755 ENG-847 hasConfig check & filename mistype
  src/helpers/getAppBuilderWidgetForm.js
  src/state/page-config/selectors.js
  src/ui/widgets/config/WidgetConfigPage.js
  test/state/page-config/selectors.test.js
  test/test/mocks/widgets.js
Labels: approved, size/XS

#756 ENG-608 updated filter values and labels
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/component-repository/categories/const.js
Labels: approved, size/S

#757 ENG-767 App builder title’s version using package.json version
  config/env.js
  src/helpers/versions.js
  src/ui/internal-page/BrandMenuContainer.js
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: approved, size/S

#759 ENG-874 add new chart colors
  src/ui/dashboard/PageStatus.js
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: size/XS

#758 ENG-772 updating nomenclature as per new glossary
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
Labels: approved, size/M

#760 ENG-865 fixed configurable widgets configuration
  src/state/page-config/actions.js
  test/state/page-config/actions.test.js
Labels: approved, size/S

#761 ENG-771 new static pages
  sass/about/AboutPage.scss
  sass/index.scss
  sass/internal-page/InternalPage.scss
  sass/license/LicensePage.scss
  src/app-init/router.js
  src/ui/about/AboutPage.js
  src/ui/app/App.js
  src/ui/internal-page/InfoMenu.js
  src/ui/license/LicensePage.js
Labels: approved, size/L

#762 ENG-692 resume loading when refreshed
  src/api/component-repository/components.js
  src/state/component-repository/components/actions.js
  src/ui/component-repository/components/list/ComponentListContainer.js
  test/ui/component-repository/components/list/ComponentListContainer.test.js
Labels: approved, size/M

#763 ENG-857 UX Quick Wins: Modify appearance and positioning of buttons
  sass/patternfly.scss
  src/ui/categories/list/ListCategoryPage.js
  src/ui/dashboard/PagesList.js
  src/ui/fragments/list/FragmentListContent.js
  src/ui/page-templates/list/PageTemplateListPage.js
  src/ui/pages/list/PageTreePage.js
  src/ui/widgets/list/ListWidgetPage.js
Labels: approved, size/M

#764 ENG-777 ENG-781 add mail and scheduler menu entries
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: approved, size/M

#765 ENG-477 amend onlineInstance prop for page reference status
  src/ui/page-templates/detail/PageTemplatePageReferencesTable.js
Labels: approved, size/XS

#766 Enable AC integration
  jenkins-x.yml
Labels: approved, size/XS

#769 ENG-887 Fix overlapping vertical nav and chevron
  sass/internal-page/InternalPage.scss
Labels: approved, size/S

#767 ENG-772 fix IT translations
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/dashboard/UxPatterns.js
  src/ui/fragments/add/AddFragmentPage.js
  src/ui/fragments/detail/DetailFragmentPage.js
  src/ui/fragments/edit/EditFragmentPage.js
  src/ui/fragments/list/ListFragmentPage.js
  src/ui/internal-page/BrandMenuContainer.js
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
  src/ui/labels/add/AddLabelPage.js
  src/ui/labels/edit/EditLabelPage.js
  src/ui/page-templates/list/PageTemplateListPage.js
  src/ui/widgets/add/AddWidgetPage.js
  src/ui/widgets/detail/DetailWidgetPage.js
  src/ui/widgets/edit/EditWidgetPage.js
Labels: approved, size/L

#768 ENG-772: fixing `Fragment` label missed in the first merge
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
Labels: approved, size/M

#770 amend OWNERS and OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
Labels: approved, size/M

#771 ENG-857 Make primary button color styles important
  sass/patternfly.scss
Labels: size/XS

#772 amend OWNERS and OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
Labels: size/M

#773 Header logo link hotfix
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: approved, size/XS

#774 ENG-787 propagate LEGACY_ADMINCONSOLE_INTEGRATION_ENABLED to index.html
  docker-entrypoint.sh
Labels: approved, size/XS

#775 ENG-891 further label fixes
  src/locales/en.js
  src/locales/it.js
  src/ui/dashboard/PageStatus.js
  src/ui/dashboard/PageStatusContainer.js
  src/ui/dashboard/PagesList.js
  src/ui/paginatorMessages.js
  test/ui/dashboard/PageStatus.test.js
  test/ui/dashboard/PagesList.test.js
Labels: size/L

#776 ENG-900: updating package version and fixing version positioning
  package.json
  sass/internal-page/InternalPage.scss
Labels: approved, size/XS

#777 Eng 891 further label fixes
  src/ui/dashboard/PageStatus.js
Labels: size/XS

#778 ENG-909 fix publishing colors
  sass/groups/detail/GroupDetailTabUsers.scss
  sass/pages/common/PageStatusIcon.scss
  sass/patternfly.scss
Labels: approved, size/S

#779 ENG-908 fix button background contrast in app-builder
  sass/users/common/UserForm.scss
Labels: approved, size/XS

#780 Eng 891 further label fixes
  src/locales/en.js
  src/locales/it.js
  src/ui/common/references/GenericRefsTable.js
  src/ui/component-repository/components/list/ComponentList.js
  src/ui/data-models/list/DataModelListTable.js
  src/ui/data-types/list/DataTypeListTable.js
  src/ui/fragments/list/FragmentListTable.js
  src/ui/groups/detail/GroupDetailTabContents.js
  src/ui/groups/detail/GroupDetailTabPages.js
  src/ui/groups/detail/GroupDetailTabResources.js
  src/ui/groups/detail/GroupDetailTabUsers.js
  src/ui/groups/detail/GroupDetailTabWidgetTypes.js
  src/ui/groups/list/GroupListTable.js
  src/ui/labels/list/LabelsAndLanguagesPage.js
  src/ui/page-templates/detail/PageTemplatePageReferencesTable.js
  src/ui/page-templates/list/PageTemplateListTable.js
  src/ui/pages/list/PageListSearchTable.js
  src/ui/profile-types/list/ProfileTypeListTable.js
  src/ui/roles/list/RoleListTable.js
  src/ui/users/list/UserListTable.js
  test/ui/common/references/GenericRefsTable.test.js
  test/ui/component-repository/components/list/ComponentList.test.js
  test/ui/data-models/list/DataModelListTable.test.js
  test/ui/fragments/list/FragmentListTable.test.js
  test/ui/groups/detail/GroupDetailTabContents.test.js
  test/ui/groups/detail/GroupDetailTabResources.test.js
  test/ui/groups/detail/GroupDetailTabWidgetTypes.test.js
  test/ui/groups/list/GroupListTable.test.js
  test/ui/labels/list/LabelsAndLanguagesPage.test.js
  test/ui/page-templates/list/PageTemplateListTable.test.js
  test/ui/pages/list/PageListSearchTable.test.js
  test/ui/roles/list/RoleListTable.test.js
Labels: approved, size/L

#781 ENG-894 - fixing side menu on safari
  sass/internal-page/InternalPage.scss
Labels: approved, size/XS

#782 ENG-891 amend user management label
  src/locales/it.js
Labels: size/XS

#783 ENG-857 Change add button position in user management pages
  src/ui/groups/list/ListGroupPage.js
  src/ui/profile-types/list/ListProfileTypePage.js
  src/ui/roles/list/ListRolePage.js
  src/ui/users/list/UserListPage.js
Labels: approved, size/S

#784 ENG-878 Hide category delete button for root category
  src/state/categories/actions.js
  src/state/categories/const.js
  src/ui/categories/list/CategoryListMenuActions.js
Labels: approved, size/S

#786 ENG-924 add contentListCard to dashboard and modify existing PageList
  sass/dashboard/PageStatus.scss
  sass/dashboard/PagesList.scss
  sass/internal-page/InternalPage.scss
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/dashboard/DashboardPage.js
  src/ui/dashboard/PageStatus.js
  src/ui/dashboard/PageStatusContainer.js
  src/ui/dashboard/PagesList.js
  src/ui/dashboard/PagesListContainer.js
Labels: approved, size/L

#787 ENG-911 rerender on locale change
  sass/index.scss
  sass/page-templates/list/PageTemplateListTable.scss
  src/ui/component-repository/components/item/install-controls/ComponentInstallActions.js
  src/ui/component-repository/components/item/install-controls/ComponentInstallActionsContainer.js
  src/ui/component-repository/components/list/ComponentList.js
  src/ui/component-repository/components/list/ComponentListContainer.js
  src/ui/database/list/DatabaseListTableContainer.js
  src/ui/file-browser/list/FilesListTableContainer.js
  src/ui/fragments/list/FragmentListTable.js
  src/ui/fragments/list/FragmentListTableContainer.js
  src/ui/fragments/list/ListFragmentPage.js
  src/ui/page-templates/list/PageTemplateListTable.js
  src/ui/page-templates/list/PageTemplateListTableContainer.js
  src/ui/reload-configuration/ReloadConfigContainer.js
  test/ui/component-repository/components/item/install-controls/ComponentInstallActions.test.js
  test/ui/reload-configuration/ReloadConfig.test.js
Labels: approved, size/L

#788 ENG-787 runtime env var improvements
  config/env.js
  docker-entrypoint.sh
  package-lock.json
  package.json
  src/app-init/apiManager.js
  src/auth/keycloak/KeycloakProviderContainer.js
  src/helpers/getRuntimeEnv.js
  src/helpers/microfrontends.js
  src/ui/app/App.js
  src/ui/internal-page/BrandMenuContainer.js
  src/ui/internal-page/InternalPage.js
  src/ui/internal-page/LanguageSelect.js
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: approved, do-not-merge/work-in-progress, size/L

#791 Eng 816 use post body to select version to install
  src/api/component-repository/components.js
Labels: approved, size/XS

#785 Update en.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/pages/common/PageSettingsForm.js
Labels: approved, size/L

#792 Eng 891 further label fixes
  src/locales/en.js
  src/locales/it.js
  src/ui/dashboard/UxPatterns.js
Labels: approved, size/XS

#793 ENG-935 CMS menu reorganize for legacy UI version
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: approved, size/M

#790 ENG-939: AppBuilder: amend menu (except CMS)
  sass/internal-page/InternalPage.scss
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/dashboard/UxPatterns.js
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: approved, size/L

#794 ENG-935 widget / mfe menu entry points to adminconsole
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: approved, size/XS

#795 ENG-935 amend labels, add missing items, remove commented code
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: approved, size/L

#796 ENG-906 fix pagelist tile issues
  src/locales/it.js
  src/ui/dashboard/PagesList.js
Labels: approved, size/S

#797 ENG-815 version api support
  src/api/component-repository/components.js
  src/models/component-repository/components.js
  src/state/component-repository/components/actions.js
  src/state/component-repository/components/reducer.js
  src/state/component-repository/components/selectors.js
  src/ui/component-repository/components/item/ComponentImage.js
  src/ui/component-repository/components/item/install-controls/ComponentInstallActions.js
  src/ui/component-repository/components/item/install-controls/ComponentInstallActionsContainer.js
  src/ui/component-repository/components/item/install-controls/ConfirmUninstallModal.js
  src/ui/component-repository/components/item/install-controls/InstallButton.js
  src/ui/component-repository/components/item/install-controls/UninstallButton.js
  src/ui/component-repository/components/list/ComponentListContainer.js
  src/ui/component-repository/components/list/ComponentListGridView.js
  src/ui/component-repository/components/list/ComponentListListView.js
  test/api/pages.test.js
  test/state/component-repository/components/actions.test.js
  test/state/component-repository/components/reducer.test.js
  test/state/component-repository/components/selectors.test.js
  test/test/mocks/component-repository/componentImages.js
  test/test/mocks/component-repository/components.js
  test/ui/component-repository/components/item/install-controls/ComponentInstallActionsContainer.test.js
  test/ui/component-repository/components/list/ComponentListContainer.test.js
  test/ui/component-repository/components/list/ComponentListGridView.test.js
  test/ui/component-repository/components/list/ComponentListListView.test.js
Labels: approved, size/XL

#798 ENG-815 update label with info from installedJob
  src/state/component-repository/components/actions.js
  src/state/component-repository/components/reducer.js
Labels: approved, size/S

#799 ENG-940 Fix alignment of language selection dropdown
  sass/internal-page/InternalPage.scss
Labels: approved, size/XS

#789 ENG-744 implement NavigationBar widget
  __mocks__/api/widgets.js
  sass/index.scss
  sass/patternfly.scss
  sass/widgets/config/forms/NavigationBarConfigForm.scss
  src/api/widgets.js
  src/helpers/getAppBuilderWidgetForm.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/page-config/actions.js
  src/state/widgets/actions.js
  src/ui/common/form/FormSectionTitle.js
  src/ui/widgets/config/forms/NavigationBarConfigForm.js
  src/ui/widgets/config/forms/NavigationBarConfigFormContainer.js
  src/ui/widgets/config/forms/NavigationBarExpressionsList.js
  src/ui/widgets/config/forms/NavigationBarTargetPage.js
  src/ui/widgets/config/forms/NavigatorBarOperator.js
  src/ui/widgets/config/forms/ToggleButtonGroupField.js
  test/api/widgets.test.js
  test/state/widgets/actions.test.js
  test/test/mocks/widgets.js
Labels: approved, size/XL

#801 ENG-744 delete new action code
  src/state/page-config/actions.js
  src/state/widget-config/actions.js
  src/ui/widgets/config/forms/NavigationBarConfigFormContainer.js
Labels: approved, size/M

#802 ENG-773 SEO fields for pages
  __mocks__/api/pages.js
  sass/index.scss
  sass/pages/common/SeoInfo.scss
  src/api/pages.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/pages/actions.js
  src/state/pages/const.js
  src/ui/common/form/RenderSelectInput.js
  src/ui/common/form/SwitchRenderer.js
  src/ui/pages/add/PagesAddFormContainer.js
  src/ui/pages/common/PageForm.js
  src/ui/pages/common/SeoInfo.js
  src/ui/pages/common/SeoInfoMetadata.js
  src/ui/pages/common/SeoInfoMetadataContainer.js
  src/ui/pages/common/SeoMetadataForm.js
  src/ui/pages/common/const.js
  src/ui/pages/edit/PagesEditFormContainer.js
  test/state/pages/actions.test.js
  test/test/mocks/pages.js
  test/ui/pages/add/PagesAddFormContainer.test.js
Labels: approved, size/XL

#803 ENG-953 updated ecr list view styling
  sass/component-repository/components/ComponentList.scss
  src/ui/component-repository/components/item/install-controls/InstallButton.js
  src/ui/component-repository/components/list/ComponentListListView.js
Labels: approved, size/M

#800 ENG-954 show error when version is not available
  src/state/component-repository/components/actions.js
Labels: approved, size/S

#804 ENG-957: Fix padding in appbuilder menu
  sass/internal-page/InternalPage.scss
Labels: approved, size/S

#806 ENG-967 removes pages from the filterable categories, removes ID from…
  src/state/component-repository/categories/const.js
  src/state/component-repository/components/reducer.js
  src/ui/component-repository/components/FilterType.js
  src/ui/component-repository/components/FilterTypeContainer.js
  test/state/component-repository/components/reducer.test.js
Labels: approved, size/S

#807 ENG-973 fixed ecr search label i18n issue
  src/ui/component-repository/components/FilterType.js
Labels: approved, size/S

#808 ENG-906 further dashboard fixes
  src/locales/en.js
  src/locales/it.js
  src/ui/dashboard/DashboardPage.js
  src/ui/dashboard/UserManagement.js
  src/ui/dashboard/UxPatterns.js
Labels: approved, size/S

#809 ENG-975 updated date to used localized version
  src/ui/component-repository/components/list/ComponentList.js
  src/ui/component-repository/components/list/ComponentListGridView.js
  src/ui/component-repository/components/list/ComponentListListView.js
  test/state/component-repository/components/actions.test.js
  test/test/mocks/component-repository/components.js
  test/ui/component-repository/components/list/ComponentListGridView.test.js
Labels: approved, size/L

#810 ENG-935: fixing paddings on sub menu items
  sass/internal-page/InternalPage.scss
Labels: approved, size/XS
