Repository entando/app-builder, pull requests merged in 2020-09, with the labels that each got.

#833 ENG-722 implement clone widget with ConfigSimpleParam
  src/app-init/router.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/page-config/selectors.js
  src/state/widgets/actions.js
  src/ui/app/App.js
  src/ui/pages/config/DraggableWidgetFrame.js
  src/ui/pages/config/DroppableWidgetFrame.js
  src/ui/pages/config/PageConfigGridCol.js
  src/ui/pages/config/WidgetFrame.js
  src/ui/widgets/clone/CloneWidgetFormContainer.js
  src/ui/widgets/clone/CloneWidgetPage.js
  src/ui/widgets/common/WidgetForm.js
  test/ui/pages/config/WidgetFrame.test.js
Labels: approved, size/L

#834 ENG-722 remove unwanted button from add widget screen
  src/ui/widgets/common/WidgetForm.js
Labels: approved, size/XS

#835 ENG-1097 show corresponding attributes when viewing
  src/locales/en.js
  src/locales/it.js
  src/ui/users/detail/DetailUserTable.js
  src/ui/users/detail/DetailUserTableContainer.js
  src/ui/users/list/UserListTable.js
Labels: approved, size/M

#836 ENG-1210 align statuses of users with AdminConsole
  src/ui/users/list/UserListTable.js
Labels: approved, size/XS

#839 ENG-1091 focus style sync from cms
  sass/pages/common/MultiSelectRenderer.scss
  sass/patternfly.scss
Labels: approved, size/S

#841 Update with-keycloak.md
  with-keycloak.md
Labels: approved, size/XS

#840 ENG-1100: adding Find Template button to add/edit/clone page form
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/pages/add/PagesAddFormContainer.js
  src/ui/pages/clone/CloneFormContainer.js
  src/ui/pages/common/FindTemplateModal.js
  src/ui/pages/common/FindTemplateModalContainer.js
  src/ui/pages/common/PageForm.js
  src/ui/pages/edit/PagesEditFormContainer.js
Labels: approved, size/L

#842 ENG-1240 implement progress tracking for ECR (un)install
  src/helpers/pollApi.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/component-repository/components/actions.js
  src/state/component-repository/components/reducer.js
  src/state/component-repository/components/selectors.js
  src/state/component-repository/components/types.js
  src/ui/component-repository/components/item/install-controls/ComponentInstallActions.js
  src/ui/component-repository/components/item/install-controls/ComponentInstallActionsContainer.js
  src/ui/component-repository/components/item/install-controls/InstallButton.js
  test/state/component-repository/components/actions.test.js
  test/state/component-repository/components/reducer.test.js
  test/state/component-repository/components/selectors.test.js
Labels: approved, size/L

#838 ENG-722 usage of native widget configs in widget form
  src/helpers/conversion.js
  src/helpers/getAppBuilderWidgetForm.js
  src/locales/en.js
  src/locales/it.js
  src/ui/widgets/clone/CloneWidgetFormContainer.js
  src/ui/widgets/common/WidgetForm.js
  src/ui/widgets/newUserWidget/NewUserWidgetFormContainer.js
Labels: approved, size/L

#844 ENG-722 removing parent widget values on widget form fields
  src/ui/widgets/clone/CloneWidgetFormContainer.js
Labels: approved, size/S

#845 Change de-app running command
  with-keycloak.md
Labels: approved, size/XS

#846 ENG-977 destroy Profile Type form when navigating from edit profile
  src/ui/roles/common/DeleteUserRoleModal.js
  src/ui/user-profile/common/UserProfileForm.js
  src/ui/user-profile/edit/EditUserProfileFormContainer.js
Labels: approved, size/S

#837 ENG-1107: Improve workflow to change authorizations
  src/ui/users/authority/UserAuthorityTable.js
  src/ui/users/common/AddAuthorityModal.js
  src/ui/users/common/UserAuthorityPageForm.js
  src/ui/users/common/UserAuthorityPageFormContainer.js
  test/ui/users/authority/UserAuthorityModal.test.js
  test/ui/users/authority/UserAuthorityTable.test.js
Labels: approved, size/L

#843 ENG-1100: fix the details link on find template modal
  src/ui/pages/common/FindTemplateModal.js
Labels: approved, size/XS

#848 ENG-1129 disable add button if no attribute chosen
  src/ui/profile-types/common/ProfileTypeForm.js
Labels: approved, size/XS

#847 ENG-1129 implement FE validations for texts and numbers
  package.json
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/profile-types/attributes/EditFormContainer.js
  src/ui/user-profile/common/UserProfileForm.js
Labels: approved, size/L

#851 ENG-1304 implement null check for null user when viewing profile
  src/ui/users/detail/DetailUserTable.js
Labels: approved, size/XS

#850 ENG-1210 let user edit user without password editing
  src/ui/users/common/UserForm.js
  src/ui/users/edit/EditFormContainer.js
  test/ui/users/common/UserForm.test.js
Labels: approved, size/S

#852 ENG-1210 send correct payload to BE when editing a user
  src/ui/users/edit/EditFormContainer.js
Labels: approved, size/XS

#853 ENG-1286 remove unused auth checker
  src/ui/users/authority/UserAuthorityTable.js
Labels: approved, size/XS
