Repository entando/app-builder, pull requests merged in 2020-10, with the labels that each got.

#854 ENG-1300 implement wizard toggling function on my profile page
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/users/my-profile/AppSettingsForm.js
  src/ui/users/my-profile/AppSettingsFormContainer.js
  src/ui/users/my-profile/MyProfilePage.js
  test/ui/users/my-profile/AppSettingsForm.test.js
Labels: approved, size/L

#856 ENG-1282 prevent locked widgets from deletion
  src/ui/widgets/list/WidgetListRow.js
  src/ui/widgets/list/WidgetListTable.js
Labels: approved, size/S

#857 ENG-1300 finish implementing wizard toggle from my profile
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/users/actions.js
  src/ui/users/my-profile/AppSettingsForm.js
  src/ui/users/my-profile/AppSettingsFormContainer.js
Labels: approved, size/S

#858 ENG-1300 Fix dont show toast if called from Tour screen toggle
  src/state/users/actions.js
  src/ui/dashboard/AppTourContainer.js
Labels: approved, size/XS

#859 ENG-1275: Page Designer - improve the 'configuration' page of the designer
  sass/pages/config/PageConfigPage.scss
  src/ui/pages/common/MultiSelectRenderer.js
  src/ui/pages/common/PageForm.js
  src/ui/pages/common/SeoInfo.js
  src/ui/pages/common/SeoInfoMetadata.js
  src/ui/pages/common/SeoMetadataForm.js
  src/ui/pages/config/PageConfigPage.js
  test/ui/pages/config/PageConfigPage.test.js
Labels: approved, size/L

#860 ENG-1352 Add readonlyDefaultConfig field into the widget edit page
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/widgets/actions.js
  src/ui/widgets/common/WidgetForm.js
  test/ui/widgets/common/WidgetForm.test.js
Labels: approved, size/S

#861 ENG-1300 fix minor icon issues
  sass/internal-page/InternalPage.scss
  src/ui/internal-page/HomePageLink.js
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
  test/ui/internal-page/HomePageLink.test.js
Labels: approved, size/S

#862 ENG-1361 Fixes for user mgmt, permissions, labels
  src/locales/en.js
  src/locales/it.js
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
  src/ui/users/detail/DetailUserTable.js
  src/ui/users/list/UserListMenuActions.js
Labels: approved, size/L

#863 ENG-1300 Fix user form related data and permissions
  src/ui/users/add/AddFormContainer.js
  src/ui/users/list/UserListMenuActions.js
Labels: size/XS

#865 update keycloak documentation reference and supported keycloak version
  README.md
Labels: approved, size/XS

#866 ENG-1315 Improve AppBuilder Dashboard
  src/ui/dashboard/Languages.js
  src/ui/dashboard/UserManagement.js
  src/ui/dashboard/UxPatterns.js
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: approved, size/M

#864 ENG-1353: FE - Change the widget config screen
  sass/pages/config/PageConfigPage.scss
  sass/patternfly.scss
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/widgets/config/WidgetConfigMicrofrontend.js
  src/ui/widgets/config/WidgetConfigPage.js
Labels: approved, size/L

#868 ENG-1098 Improve My Profile Page
  sass/index.scss
  sass/users/my-profile/MyProfilePage.scss
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/users/actions.js
  src/ui/app/App.js
  src/ui/users/my-profile/AccountForm.js
  src/ui/users/my-profile/AccountFormContainer.js
  src/ui/users/my-profile/MyProfileEditForm.js
  src/ui/users/my-profile/MyProfileEditFormContainer.js
  src/ui/users/my-profile/MyProfilePage.js
  src/ui/users/my-profile/MyProfilePageContainer.js
  src/ui/users/my-profile/PasswordForm.js
  src/ui/users/my-profile/PasswordFormContainer.js
  test/state/users/actions.test.js
  test/ui/app/App.test.js
  test/ui/users/my-profile/AccountForm.test.js
  test/ui/users/my-profile/AccountFormContainer.test.js
  test/ui/users/my-profile/AppSettingsForm.test.js
  test/ui/users/my-profile/MyProfilePage.test.js
  test/ui/users/my-profile/PasswordFormContainer.test.js
Labels: approved, size/XL

#867 ENG-1276 New Widget List UX
  sass/common/SectionCollapse.scss
  sass/index.scss
  sass/internal-page/InternalPage.scss
  sass/pages/common/PageTreeCompact.scss
  sass/pages/config/ContentWidget.scss
  sass/pages/config/ContentWidgetElement.scss
  sass/pages/config/PageConfigPage.scss
  sass/pages/config/ToolbarPageConfig.scss
  sass/patternfly.scss
  sass/users/common/UserForm.scss
  src/locales/en.js
  src/locales/it.js
  src/state/page-config/actions.js
  src/state/page-config/reducer.js
  src/state/page-config/selectors.js
  src/state/page-config/types.js
  src/ui/common/accessibility/KeyCodes.js
  src/ui/common/section-collapse/SectionCollapse.js
  src/ui/common/section-collapse/SectionCollapseTitle.js
  src/ui/pages/common/PageTreeCompact.js
  src/ui/pages/config/ContentWidget.js
  src/ui/pages/config/ContentWidgetContainer.js
  src/ui/pages/config/ContentWidgetElement.js
  src/ui/pages/config/ContentWidgetElementIcon.js
  src/ui/pages/config/PageConfigPage.js
  src/ui/pages/config/ToolbarPageConfig.js
  test/state/page-config/reducer.test.js
  test/state/page-config/selectors.test.js
  test/ui/pages/config/ContentWidget.test.js
  test/ui/pages/config/ContentWidgetContainer.test.js
  test/ui/pages/config/ToolbarPageConfig.test.js
Labels: approved, size/XL

#871 ENG-1377 amend cosmetic feedback
  package.json
  src/locales/en.js
  src/locales/it.js
  src/ui/dashboard/PagesList.js
  src/ui/pages/common/PageTreeActionMenu.js
Labels: approved, size/XS

#869 ENG-1067 View published page and preview buttons added
  package.json
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/pages/selectors.js
  src/ui/pages/common/PageTree.js
  src/ui/pages/common/PageTreeActionMenu.js
  src/ui/pages/common/PageTreeCompact.js
  src/ui/pages/common/PageTreeContainer.js
  src/ui/pages/config/ContentPagesContainer.js
  src/ui/pages/config/PageConfigPage.js
  src/ui/pages/config/PageConfigPageContainer.js
  test/state/pages/selectors.test.js
  test/ui/pages/common/PageTreeActionMenu.test.js
  test/ui/pages/common/PageTreeContainer.test.js
  test/ui/pages/config/ContentPageContainer.test.js
  test/ui/pages/config/PageConfigPage.test.js
  test/ui/pages/config/PageConfigPageContainer.test.js
Labels: approved, size/L

#872 ENG-1375 properly fetch attribute roles
  src/ui/common/attributes/AttributeRole.js
  src/ui/common/form/RoleSelectRenderer.js
  src/ui/profile-types/attributes/EditFormContainer.js
Labels: approved, size/S

#873 ENG-1270: adding user preferences and connecting to API
  src/api/userPreferences.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/rootReducer.js
  src/state/user-preferences/actions.js
  src/state/user-preferences/reducer.js
  src/state/user-preferences/selectors.js
  src/state/user-preferences/types.js
  src/ui/app/App.js
  src/ui/app/AppContainer.js
  src/ui/users/my-profile/AppSettingsForm.js
  src/ui/users/my-profile/AppSettingsFormContainer.js
  test/api/userPreferences.test.js
  test/state/user-preferences/reducer.test.js
  test/state/user-preferences/selectors.test.js
  test/test/mocks/userPreferences.js
  test/ui/users/my-profile/AppSettingsForm.test.js
Labels: approved, size/L

#874 ENG-1377 page list card pagination on page size
  src/ui/dashboard/PagesList.js
  src/ui/dashboard/PagesListContainer.js
Labels: approved, size/S

#870 ENG-1253 implement tutorial
  package.json
  sass/tour/index.scss
  src/app-init/apiManager.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/app-tour/actions.js
  src/state/app-tour/const.js
  src/state/app-tour/reducer.js
  src/state/app-tour/selectors.js
  src/state/app-tour/types.js
  src/state/page-config/actions.js
  src/state/pages/actions.js
  src/state/rootReducer.js
  src/state/store.js
  src/state/user-preferences/actions.js
  src/ui/app-tour/AppTour.js
  src/ui/app-tour/AppTourContainer.js
  src/ui/app/App.js
  src/ui/common/form/RenderSelectInput.js
  src/ui/common/form/RenderTextInput.js
  src/ui/dashboard/AppTour.js
  src/ui/dashboard/AppTourContainer.js
  src/ui/dashboard/DashboardPage.js
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
  src/ui/pages/add/PagesAddFormContainer.js
  src/ui/pages/add/PagesAddPage.js
  src/ui/pages/common/PageForm.js
  src/ui/pages/common/PageTreeContainer.js
  src/ui/pages/common/SeoInfo.js
  src/ui/pages/config/PageConfigPage.js
  src/ui/pages/config/PageConfigPageContainer.js
  src/ui/pages/list/PageTreePage.js
  src/ui/pages/list/PageTreePageContainer.js
  src/ui/widgets/config/forms/NavigationBarConfigForm.js
  src/ui/widgets/config/forms/NavigationBarConfigFormContainer.js
  src/ui/widgets/config/forms/NavigationBarTargetPage.js
  src/ui/widgets/config/forms/NavigatorBarOperator.js
  test/state/app-tour/actions.test.js
  test/state/app-tour/reducer.test.js
  test/state/app-tour/selectors.test.js
  test/ui/app-tour/AppTour.test.js
  test/ui/pages/add/PagesAddFormContainer.test.js
  test/ui/pages/config/PageConfigPageContainer.test.js
Labels: approved, size/XXL

#876 ENG-1270: preventing fetchUserPreferences to be ran on the login screen
  src/ui/app/App.js
Labels: approved, size/XS

#875 ENG-1276 cosmetic bug on page designer toolbar + icon changes
  sass/common/SectionCollapse.scss
  sass/pages/config/ContentWidgetElement.scss
  sass/pages/config/PageConfigPage.scss
  sass/pages/config/ToolbarPageConfig.scss
  src/ui/pages/common/PageTreeCompact.js
  src/ui/pages/config/ContentWidgetElementIcon.js
  src/ui/pages/config/PageConfigPage.js
  src/ui/pages/config/ToolbarPageConfig.js
  test/ui/pages/config/PageConfigPage.test.js
Labels: approved, size/L

#877 ENG-1244: fixing styles after merge issues
  sass/pages/config/PageConfigPage.scss
Labels: approved, size/M

#879 ENG-1098 Fix MyProfileEditForm not reinitializing
  src/helpers/entities.js
  src/state/user-profile/actions.js
  src/ui/users/my-profile/AccountForm.js
  src/ui/users/my-profile/MyProfileEditForm.js
  src/ui/users/my-profile/MyProfileEditFormContainer.js
Labels: approved, size/S

#878 ENG-1274 Enhancements and UX Changes in Page Tree part of Page Designer
  package-lock.json
  sass/pages/common/PageTreeCompact.scss
  sass/pages/config/ContentPages.scss
  sass/pages/list/PageListSearchTable.scss
  sass/patternfly.scss
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/user-preferences/actions.js
  src/ui/pages/common/PageTreeActionMenu.js
  src/ui/pages/common/PageTreeCompact.js
  src/ui/pages/config/ContentPages.js
  src/ui/pages/config/ContentPagesContainer.js
  src/ui/pages/config/ToolbarPageConfig.js
  src/ui/pages/config/ToolbarPageConfigContainer.js
  src/ui/pages/list/PageListSearchTable.js
  test/ui/pages/config/ContentPageContainer.test.js
  test/ui/pages/config/ContentPages.test.js
  test/ui/pages/config/ToolbarPageConfigContaier.test.js
Labels: approved, size/XL

#880 ENG-1276 avoiding name “Entando CMS” in widget list
  src/state/page-config/selectors.js
Labels: approved, size/XS

#881 ENG-1376 Page Form Fixes
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/pages/actions.js
  src/ui/pages/clone/CloneFormContainer.js
  src/ui/pages/common/PageTreeCompact.js
  src/ui/pages/edit/PagesEditFormContainer.js
  test/state/pages/actions.test.js
  test/ui/pages/clone/CloneFormContainer.test.js
  test/ui/pages/edit/PagesEditFormContainer.test.js
Labels: approved, size/M

#882 ENG-1253 tutorial back fixes
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/app-tour/AppTour.js
  src/ui/app-tour/AppTourContainer.js
  src/ui/widgets/config/forms/NavigationBarConfigForm.js
  test/ui/app-tour/AppTour.test.js
Labels: approved, size/M

#883 ENG-978 allow users with one permission among [validateContents, editContents, manageResources] to CRUD assets
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: approved, size/M

#884 ENG-1274 Fix Page Designer page tree issues (selection, dropdown, etc.)
  src/locales/en.js
  src/ui/pages/common/PageTreeActionMenu.js
  src/ui/pages/common/PageTreeCompact.js
  src/ui/pages/config/ContentPages.js
  src/ui/pages/list/PageListSearchTable.js
  test/ui/pages/common/PageTreeActionMenu.test.js
Labels: approved, size/M

#885 ENG-1274 Fix Page Designer page tree menu items not working properly
  src/ui/pages/add/PagesAddFormContainer.js
  src/ui/pages/common/PageTreeActionMenu.js
  src/ui/pages/common/PageTreeCompact.js
  test/ui/pages/add/PagesAddFormContainer.test.js
Labels: approved, size/M

#886 ENG-1375 fixes email attribute
  src/state/profile-types/actions.js
  src/ui/common/attributes/AttributeListTableActions.js
  src/ui/common/attributes/AttributeRole.js
  src/ui/common/form/RoleSelectRenderer.js
  src/ui/profile-types/attributes/EditFormContainer.js
  src/ui/user-profile/common/UserProfileForm.js
Labels: approved, size/M

#888 ENG-1378 CSS rule for starting points (left/top) of content area
  sass/internal-page/InternalPage.scss
Labels: approved, size/S

#889 ENG-1378 jx trigger
  sass/internal-page/InternalPage.scss
Labels: approved, size/XS

#887 ENG-1300 add new features
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/app-tour/AppTour.js
  src/ui/app-tour/AppTourContainer.js
  src/ui/internal-page/InfoMenu.js
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
  src/ui/widgets/config/forms/NavigationBarConfigFormContainer.js
  src/ui/widgets/config/forms/NavigationBarTargetPage.js
  test/ui/app-tour/AppTour.test.js
Labels: approved, do-not-merge/work-in-progress, size/L

#890 ENG-1300 fix closure of last step
  src/ui/app-tour/AppTour.js
  src/ui/app-tour/AppTourContainer.js
Labels: approved, size/S

#891 ENG-1356 Fix bugs for showing the report
  src/app-init/router.js
  src/state/database/actions.js
  src/ui/app/App.js
  src/ui/database/dump/DatabaseDumpTablePage.js
  src/ui/database/dump/DatabaseDumpTablePageContainer.js
  src/ui/database/report/ReportDatabaseDataSource.js
  src/ui/database/report/ReportDatabaseListDataSource.js
  src/ui/database/report/ReportDatabaseListTable.js
  src/ui/user-profile/common/UserProfileForm.js
  test/state/database/actions.test.js
  test/ui/database/dump/DatabaseDumpTablePage.test.js
  test/ui/database/dump/DatabaseDumpTablePageContainer.test.js
Labels: approved, size/M

#892 ENG-1274 Improve Page Designer page tree UX
  sass/pages/config/ContentPages.scss
  src/locales/en.js
  src/state/pages/actions.js
  src/ui/pages/add/PagesAddFormContainer.js
  src/ui/pages/clone/CloneFormContainer.js
  src/ui/pages/common/DeletePageModal.js
  src/ui/pages/common/DeletePageModalContainer.js
  src/ui/pages/common/PageTreeActionMenu.js
  src/ui/pages/common/PageTreeCompact.js
  src/ui/pages/config/ContentPages.js
  src/ui/pages/config/ContentPagesContainer.js
  test/state/pages/actions.test.js
  test/ui/pages/common/PageTreeCompact.test.js
Labels: approved, size/L

#893 ENG-1365 Fix logic for showing settings menu item of a widget frame
  src/state/page-config/selectors.js
  src/ui/pages/config/PageConfigGridCol.js
  src/ui/pages/config/WidgetFrame.js
  test/ui/pages/config/WidgetFrame.test.js
Labels: approved, size/S
