Repository entando/app-builder, pull requests merged in 2020-12, with the labels that each got.

#957 ENG-1572 Fix page form Add Metadata section alignment
  src/ui/pages/common/SeoMetadataForm.js
Labels: approved, size/XS

#958 ENG-1567 properly group widgets in fragment search
  src/state/fragments/selectors.js
  src/ui/fragments/list/FragmentSearchForm.js
  test/state/fragments/selectors.test.js
  test/ui/fragments/list/FragmentSearchForm.test.js
Labels: approved, size/L

#959 Update @entando/pagetreeselector
  package-lock.json
  package.json
Labels: approved, size/M

#960 ENG-1625 hide user-related widgets
  src/state/widgets/actions.js
  test/state/widgets/actions.test.js
Labels: approved, size/S

#961 ENG-1629 fix broken internationalization
  src/ui/fragments/list/FragmentSearchForm.js
Labels: size/S

#964 ENG-1623 Reimplement local storage state persistence logic
  src/state/store.js
  test/state/store.test.js
Labels: approved, size/M

#963 ENG-1577: AppBuilder: In MFE and Widgets page, the Custom UI is displayed as no mandatory
  src/ui/common/form/RenderTextAreaInput.js
  src/ui/widgets/common/WidgetForm.js
Labels: approved, size/S

#962 ENG-1619: adding padding to the progress bar
  sass/component-repository/components/ComponentList.scss
Labels: approved, size/S

#965 ENG-1618 fix decimal bug from javascript
  src/ui/component-repository/components/item/install-controls/InstallButton.js
Labels: approved, size/XS

#966 ENG-1633 Update redux-form
  package-lock.json
  package.json
Labels: approved, size/M

#936 ENG-1482: adding new displayAttributes flag
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/user-preferences/reducer.js
  src/ui/users/my-profile/AppSettingsForm.js
  test/test/mocks/userPreferences.js
Labels: approved, size/S

#967 ENG-1643 Fix error caused by rechecking install status
  src/ui/component-repository/components/item/install-controls/ComponentInstallActionsContainer.js
Labels: approved, size/M

#968 ENG-1593 Fix the responsiveness of the dashboard page
  sass/dashboard/DashboardPage.scss
  sass/dashboard/PagesList.scss
  sass/index.scss
  src/ui/dashboard/PagesList.js
Labels: approved, size/M

#969 ENG-1620 Improve bundle un/installation progress label
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/component-repository/components/item/install-controls/ComponentInstallActions.js
  src/ui/component-repository/components/item/install-controls/InstallButton.js
  src/ui/component-repository/components/list/ComponentListGridView.js
Labels: approved, size/M

#970 ENG-1146 retry fix
  sass/component-repository/components/ComponentList.scss
  src/ui/component-repository/components/item/install-controls/ComponentInstallActions.js
  src/ui/component-repository/components/item/install-controls/ComponentInstallActionsContainer.js
  src/ui/component-repository/components/item/install-controls/FailedInstallState.js
Labels: approved, size/L

#971 Add missing step in with-keycloak.md
  with-keycloak.md
Labels: approved, size/XS
