Repository entando/app-builder, pull requests merged in 2020-03, with the labels that each got.

#651 ENG-202 fix profile type attribute details not rendered
  src/ui/common/form/EditAttributeForm.js
  src/ui/profile-types/attributes/EditFormContainer.js
Labels: needs-ok-to-test, size/S

#652 ENG-192 remove redundant empty object checker
  src/state/widgets/actions.js
Labels: needs-ok-to-test, size/XS

#653 ENG-261 remove bundle id from widget screens
  OWNERS
  OWNERS_ALIASES
  jenkins-x.yml
  scripts/test.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/widgets/actions.js
  src/ui/widgets/common/WidgetForm.js
  test/ui/widgets/config/WidgetConfigMicrofrontend.test.js
Labels: size/M

#656 ENG-219 Add edit item to WidgetFrame action menu
  src/ui/pages/config/WidgetFrame.js
Labels: approved, size/S

#654 ENG-237 use single source of truth for date formatting
  src/helpers/dateFormatter.js
  src/ui/common/references/UserRefsTable.js
  src/ui/dashboard/PagesList.js
  src/ui/database/list/DatabaseListTable.js
  src/ui/users/common/UserForm.js
Labels: approved, needs-ok-to-test, size/S

#657 ENG-266 Fix typos and inconsistencies
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/fragments/common/FragmentForm.js
  src/ui/fragments/list/FragmentListContent.js
  src/ui/widgets/common/WidgetForm.js
  src/ui/widgets/list/ListWidgetPage.js
Labels: approved, size/S

#658 ENG-237 use updated frontend libraries and formatDate
  __mocks__/@entando/utils.js
  package-lock.json
  package.json
  src/helpers/dateFormatter.js
  src/ui/common/references/UserRefsTable.js
  src/ui/dashboard/PagesList.js
  src/ui/database/list/DatabaseListTable.js
  src/ui/users/common/UserForm.js
Labels: approved, size/M

#659 ENG-222: add keycloak config info to readme + small improvements
  README.md
  config/env.js
  src/auth/AuthProvider.js
  src/auth/keycloakEnabled.js
  src/auth/withAuth.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
Labels: approved, size/M

#660 ENG-282 rename labels
  README.md
  src/app-init/router.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/app/App.js
  test/state/digital-exchange/components/reducer.test.js
  test/state/digital-exchange/digital-exchanges/reducer.test.js
  test/ui/app/App.test.js
  test/ui/digital-exchange/components/list/ComponentListGridView.test.js
Labels: approved, size/L

#661 ENG-220 add loading spinners to app-builder pages
  src/state/page-config/actions.js
  src/state/pages/actions.js
  src/state/user-settings/actions.js
  src/ui/pages/common/PageSettingsForm.js
  src/ui/pages/common/PageSettingsFormContainer.js
  src/ui/pages/common/PageTree.js
  src/ui/pages/config/PageConfigPage.js
  src/ui/pages/config/PageConfigPageContainer.js
  src/ui/pages/list/PageTreePage.js
  src/ui/pages/list/PageTreePageContainer.js
  src/ui/users/restrictions/RestrictionsForm.js
  src/ui/users/restrictions/RestrictionsFormContainer.js
  test/state/page-config/actions.test.js
  test/state/user-settings/actions.test.js
  test/ui/pages/common/PageSettingsForm.test.js
  test/ui/pages/common/PageSettingsFormContainer.test.js
  test/ui/pages/config/PageConfigPageContainer.test.js
  test/ui/pages/list/PageTreePageContainer.test.js
  test/ui/users/restrictions/RestrictionsForm.test.js
  test/ui/users/restrictions/RestrictionsFormContainer.test.js
Labels: approved, size/XL

#662 ENG-91 Implement LanguageSelect
  sass/internal-page/InternalPage.scss
  src/ui/internal-page/HomePageLinkContainer.js
  src/ui/internal-page/InternalPage.js
  src/ui/internal-page/LanguageSelect.js
  src/ui/internal-page/LanguageSelectContainer.js
  test/ui/internal-page/LanguageSelect.test.js
  test/ui/internal-page/LanguageSelectContainer.test.js
Labels: approved, size/L

#664 ENG-221
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/data-types/actions.js
  src/state/fragments/actions.js
  src/state/pages/actions.js
  src/ui/data-models/add/AddDataModelFormContainer.js
  src/ui/data-models/edit/EditDataModelFormContainer.js
  src/ui/data-types/add/AddFormContainer.js
  src/ui/data-types/edit/EditFormContainer.js
  src/ui/fragments/add/AddFormContainer.js
  src/ui/fragments/edit/EditFormContainer.js
  src/ui/page-models/common/PageModelFormContainer.js
  src/ui/pages/edit/PagesEditFormContainer.js
  src/ui/widgets/common/WidgetFormContainer.js
  src/ui/widgets/edit/EditWidgetFormContainer.js
  test/state/pages/actions.test.js
Labels: approved, size/M

#665 ENG-286 implement cancel and delete confirms
  sass/fragment/FragmentForm.scss
  src/locales/en.js
  src/locales/it.js
  src/state/fragments/actions.js
  src/ui/common/cancel-modal/ConfirmCancelModal.js
  src/ui/common/cancel-modal/ConfirmCancelModalContainer.js
  src/ui/fragments/add/AddFormContainer.js
  src/ui/fragments/common/FragmentForm.js
  src/ui/fragments/edit/EditFormContainer.js
  src/ui/fragments/list/DeleteFragmentModal.js
  src/ui/fragments/list/DeleteFragmentModalContainer.js
  src/ui/fragments/list/FragmentListTable.js
  src/ui/fragments/list/FragmentListTableContainer.js
  src/ui/widgets/common/WidgetForm.js
  src/ui/widgets/common/WidgetFormContainer.js
  src/ui/widgets/list/DeleteWidgetModal.js
  src/ui/widgets/list/DeleteWidgetModalContainer.js
  src/ui/widgets/list/ListWidgetPage.js
  src/ui/widgets/list/ListWidgetPageContainer.js
  src/ui/widgets/list/WidgetListTable.js
  test/state/fragments/actions.test.js
  test/ui/fragments/add/AddFormContainer.test.js
  test/ui/fragments/common/FragmentForm.test.js
  test/ui/fragments/edit/EditFormContainer.test.js
  test/ui/fragments/list/FragmentListTableContainer.test.js
  test/ui/widgets/common/WidgetForm.test.js
  test/ui/widgets/common/WidgetFormContainer.test.js
  test/ui/widgets/list/ListWidgetPageContainer.test.js
Labels: approved, size/L

#666 ENG-222 improve keycloak integration docs
  README.md
Labels: approved, size/XS

#668 ENG-302 fix edit widget form container
  src/ui/widgets/edit/EditWidgetFormContainer.js
Labels: approved, size/S

#667 ENG-320 add edit action for widgets list
  src/ui/widgets/list/ListWidgetPage.js
  src/ui/widgets/list/ListWidgetPageContainer.js
  src/ui/widgets/list/WidgetListRow.js
  src/ui/widgets/list/WidgetListTable.js
Labels: approved, size/M
