Repository entando/app-builder, pull requests merged in 2020-06, with the labels that each got.

#715 CMS 0.0.71 publish
  src/ui/users/list/UserListMenuActions.js
Labels: approved, size/XS

#716 Force build for test
  src/ui/auth/withPermissions.js
Labels: size/XS

#717 ENG-581 change requested permissions for widget configs
  src/ui/widgets/config/WidgetConfigPageContainer.js
  src/ui/widgets/detail/DetailWidgetPageContainer.js
Labels: approved, size/XS

#718 ENG-490 prevent accidental page moving
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/pages/common/MovePageModal.js
  src/ui/pages/common/MovePageModalContainer.js
  src/ui/pages/common/PageTree.js
  src/ui/pages/common/PageTreeContainer.js
  test/ui/pages/common/MovePageModal.test.js
  test/ui/pages/common/MovePageModalContainer.test.js
  test/ui/pages/common/PageTree.test.js
  test/ui/pages/common/PageTreeContainer.test.js
Labels: approved, size/L

#719 ENG-653 upgrade react testing library to latest version
  package.json
Labels: approved, size/XS

#720 CMS widget config fix build trigger
  src/ui/widgets/config/WidgetConfigPage.js
Labels: approved, size/XS

#721 trigger for CMS widget config on frontend filter choices
  src/ui/pages/list/PageTreePageContainer.js
Labels: approved, size/XS

#722 ENDOC-34 readme link updates
  README.md
Labels: size/XS

#723 trigger JX build for Entando-cms 0.2.73
  src/ui/widgets/config/WidgetConfigPage.js
Labels: approved, size/XS

#724 Revert "trigger JX build for entando-cms 0.2.73"
  src/ui/widgets/config/WidgetConfigPage.js
Labels: approved, size/XS

#726 Trigger CMS Build
  src/ui/dashboard/IntegrationsContainer.js
Labels: size/XS

#727 Trigger CMS build for v 82
  src/ui/internal-page/BrandMenuContainer.js
Labels: size/XS

#729 ENG-640 fix dates
  package.json
  src/ui/dashboard/LanguagesContainer.js
Labels: approved, size/XS

#730 ENG-638 implement frontend permissions for user auth
  src/ui/user-profile/edit/EditUserProfilePage.js
  src/ui/users/authority/UserAuthorityPageContainer.js
  src/ui/users/detail/DetailUserPage.js
Labels: approved, size/S

#731 ENG-716 persist data from apps
  src/state/store.js
  test/state/store.test.js
Labels: approved, size/M

#728 ENG-746 menu integration
  config/env.js
  public/images/entando-logo-white.svg
  public/index.html
  sass/internal-page/InternalPage.scss
  sass/patternfly.scss
  src/app-init/router.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/internal-page/InfoDropdown.js
  src/ui/internal-page/InfoMenu.js
  src/ui/internal-page/InternalPage.js
  src/ui/internal-page/LanguageSelect.js
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: approved, do-not-merge/work-in-progress, size/XL

#732 ENG-683 operations on pages/categories access permissions
  src/ui/dashboard/DashboardPage.js
  src/ui/internal-page/BrandMenuContainer.js
  src/ui/page-templates/add/PageTemplateAddPage.js
  src/ui/page-templates/detail/PageTemplateDetailPage.js
  src/ui/page-templates/detail/PageTemplateDetailPageContainer.js
  src/ui/page-templates/edit/PageTemplateEditPage.js
  src/ui/page-templates/list/PageTemplateListPage.js
  src/ui/pages/settings/PageSettings.js
Labels: approved, size/L

#733 ENG-724 fix multiline code string
  sass/index.scss
  sass/page-templates/detail/PageTemplateDetailTable.scss
  src/ui/page-templates/detail/PageTemplateDetailTable.js
Labels: approved, size/S

#734 ENG-680 fix plugin auth error
  src/ui/app/App.js
  src/ui/internal-page/BrandMenuContainer.js
Labels: approved, size/S

#735 JX build trigger commit for CMS 0.2.92
  src/ui/internal-page/BrandMenuContainer.js
Labels: approved, size/XS

#738 ENG-720 fix default pre word wrapping
  src/ui/fragments/common/FragmentForm.js
  src/ui/widgets/common/WidgetForm.js
Labels: approved, size/XS

#736 ENG-723 fix mainframe bug
  src/state/page-templates/selectors.js
  test/test/mocks/page-templates/complex.js
Labels: approved, size/XS

#737 ENG-608 vizualization issues, removed components
  config/webpack.config.dev.js
  package-lock.json
  src/state/component-repository/components/actions.js
  src/state/component-repository/components/reducer.js
  src/state/component-repository/extra-filters/const.js
  src/state/loading/actions.js
  src/state/loading/reducer.js
  src/state/loading/types.js
  src/ui/component-repository/components/list/ComponentList.js
  src/ui/component-repository/components/list/ComponentListContainer.js
  src/ui/component-repository/components/list/ComponentListGridView.js
  src/ui/component-repository/components/list/ComponentListListView.js
  src/ui/component-repository/components/list/ComponentListPage.js
  src/ui/internal-page/PageTitle.js
  test/state/component-repository/components/actions.test.js
  test/state/component-repository/extra-filters/reducer.test.js
  test/ui/component-repository/components/list/ComponentListContainer.test.js
  test/ui/component-repository/components/list/ComponentListGridView.test.js
  test/ui/component-repository/components/list/ComponentListListView.test.js
Labels: approved, size/XL

#739 ENG-723 fix selected page template
  src/state/page-templates/actions.js
  test/state/page-templates/actions.test.js
Labels: approved, size/XS

#740 ENG-718 group default value logic for edit widget
  src/state/widgets/actions.js
  test/state/widgets/actions.test.js
  test/test/mocks/widgets.js
Labels: approved, size/M
