Repository entando/app-builder, pull requests merged in 2020-08, with the labels that each got.

#811 ENG-773 fix on switch indetermined state when a field value from different tab changes
  src/ui/pages/common/SeoInfo.js
Labels: approved, size/XS

#812 ENG-925 Fix overlapping vertical nav and CMS footer
  sass/internal-page/InternalPage.scss
Labels: approved, size/S

#814 ENG-894: AppBuilder: Vertical main menu is blocked in Safari browser
  sass/common/cross-browser.scss
  sass/index.scss
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: approved, size/S

#813 Eng 976 labels localization formatting
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/about/AboutPage.js
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
  src/ui/license/LicensePage.js
Labels: approved, size/M

#815 ENG-971 restore old page status colors, amend labels
  sass/patternfly.scss
  src/locales/it.js
  src/ui/dashboard/PageStatus.js
Labels: approved, size/M

#816 ENG-987 added some css to align PageTree table components
  sass/pages/common/PageTree.scss
  src/ui/pages/common/PageTree.js
Labels: approved, size/S

#817 ENG-744 ENG-985 map widget config by action
  src/helpers/getAppBuilderWidgetForm.js
  src/ui/widgets/config/WidgetConfigPage.js
Labels: approved, size/S

#818 ENG-991: Page Status add last modified date
  sass/dashboard/PageStatus.scss
  src/ui/dashboard/PageStatus.js
Labels: approved, size/XS

#819 Update README.md
  README.md
Labels: approved, size/XS

#820 update readme
  README.md
Labels: approved, do-not-merge/hold, size/XS

#821 ENG-479 fragment reference table column order change
  src/ui/fragments/detail/WidgetTypeReferenceTable.js
Labels: approved, size/XS

#822 JX publish trigger for CMS 0.2.147
  src/ui/fragments/detail/WidgetTypeReferenceTable.js
Labels: approved, size/XS

#823 ENG-1042 temporarily redirect user management links to admin console
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: approved, size/S

#824 ENG-1039 Fix row action dropdown of widget details
  src/ui/widgets/detail/DetailWidgetElement.js
Labels: approved, size/S

#825 JX trigger build for Entando CMS 0.2.148
  src/api/pages.js
Labels: approved, size/XS

#826 ENG-1026 fix search value operator
  src/ui/labels/list/LabelSearchFormContainer.js
Labels: approved, size/XS

#827 ENG-1022 fix default view for file browser
  src/ui/file-browser/list/FilesListTable.js
  test/ui/file-browser/list/FilesListTable.test.js
Labels: approved, size/M

#829 ENG-977 fix user and profile related issues and add new features
  src/helpers/entities.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/users/actions.js
  src/ui/profile-types/common/ProfileTypeReferenceStatus.js
  src/ui/user-profile/common/UserProfileForm.js
  src/ui/user-profile/edit/EditUserProfileFormContainer.js
  src/ui/users/add/AddFormContainer.js
  src/ui/users/common/UserForm.js
  test/ui/users/add/AddFormContainer.test.js
  test/ui/users/common/UserForm.test.js
Labels: approved, size/L

#830 ENG-1097 show profile types on user tables
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/users/detail/DetailUserTable.js
  src/ui/users/list/UserListTable.js
Labels: approved, size/S

#832 ENG-1083 implement user reference table when deleting user role
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/common/modal/GenericModalContainer.js
  src/ui/roles/common/DeleteUserRoleModal.js
  src/ui/roles/common/DeleteUserRoleModalContainer.js
  src/ui/roles/list/RoleListTable.js
  src/ui/roles/list/RoleListTableContainer.js
  test/ui/roles/list/RoleListTableContainer.test.js
Labels: approved, size/L
