Repository entando/app-builder, pull requests merged in 2020-04, with the labels that each got.

#670 ENG-286 new login page
  package-lock.json
  package.json
  public/fonts/Font_Roboto/LICENSE.txt
  public/fonts/Font_Roboto/Roboto-Black.ttf
  public/fonts/Font_Roboto/Roboto-BlackItalic.ttf
  public/fonts/Font_Roboto/Roboto-Bold.ttf
  public/fonts/Font_Roboto/Roboto-BoldItalic.ttf
  public/fonts/Font_Roboto/Roboto-Italic.ttf
  public/fonts/Font_Roboto/Roboto-Light.ttf
  public/fonts/Font_Roboto/Roboto-LightItalic.ttf
  public/fonts/Font_Roboto/Roboto-Medium.ttf
  public/fonts/Font_Roboto/Roboto-MediumItalic.ttf
  public/fonts/Font_Roboto/Roboto-Regular.ttf
  public/fonts/Font_Roboto/Roboto-Thin.ttf
  public/fonts/Font_Roboto/Roboto-ThinItalic.ttf
  public/images/Stack.png
  public/images/caret-down.svg
  public/images/logo.svg
Labels: approved, size/L

#671 ENG-97 fix moderate vulnerabilities
  package-lock.json
  package.json
Labels: approved, size/L

#672 ENG-286 login page
  package-lock.json
  package.json
  public/images/bg-login.jpg
  public/images/login-bg.png
  public/images/login-logo.svg
  public/images/topbar-logo.svg
  src/ui/internal-page/InternalPage.js
Labels: approved, size/S

#673 ENG-286 increase entando-pages version
  package-lock.json
  package.json
Labels: approved, size/S

#674 ENG-282 amend labels
  src/locales/en.js
  src/locales/it.js
Labels: approved, size/S

#663 ENG-276 update version, favicon, logo
  package.json
  public/favicon-entando.png
  public/images/topbar-logo.svg
  src/ui/internal-page/InternalPage.js
Labels: approved, size/S

#675 ENG-137 Fragments list search filter parameters fix
  src/ui/fragments/list/FragmentSearchForm.js
  src/ui/fragments/list/FragmentSearchFormContainer.js
  test/ui/fragments/list/FragmentSearchForm.test.js
Labels: approved, size/M

#676 ENG-224 let user to upload multiple files
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/common/form/RenderFileInput.js
  src/ui/file-browser/common/FileButtonsGroup.js
  src/ui/file-browser/upload/UploadFileBrowserForm.js
  src/ui/file-browser/upload/UploadFileBrowserFormContainer.js
  src/ui/file-browser/upload/UploadFileBrowserPage.js
  test/ui/file-browser/upload/UploadFileBrowserFormContainer.test.js
Labels: approved, size/S

#678 ENG-362 use promise while creating a new page
  src/state/page-config/actions.js
  src/state/pages/actions.js
  src/ui/pages/add/PagesAddFormContainer.js
Labels: approved, size/M

#677 ENG-357 display error (bad request) on modifying page parent
  package-lock.json
  package.json
  src/state/pages/actions.js
  src/ui/pages/edit/PagesEditFormContainer.js
  test/state/pages/actions.test.js
Labels: approved, size/M

#679 Eng 55 label fixes
  src/locales/en.js
  src/locales/it.js
Labels: approved, size/S

#680 ENG-327 Amend widget list labels
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/widgets/list/WidgetListTable.js
  src/ui/widgets/list/WidgetSectionTitle.js
Labels: size/S

#681 ENG-372 fix active default language overriding
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/languages/actions.js
  src/state/pages/actions.js
  src/ui/pages/add/PagesAddFormContainer.js
  test/state/languages/actions.test.js
Labels: size/M

#684 ENG-381 page form modal fix on page config > page settings
  src/api/pages.js
  src/ui/pages/config/SinglePageSettingsForm.js
Labels: approved, size/S

#683 ENG-211 fix page add new page toasts and flow
  src/state/pages/actions.js
  src/ui/pages/add/PagesAddFormContainer.js
  test/state/pages/actions.test.js
Labels: approved, size/M

#685 ENG-211 fix silent 400 error
  src/state/pages/actions.js
Labels: approved, size/XS

#687 ENG-249 update component manager endpoints
  src/api/digital-exchange/components.js
Labels: size/XS

#689 PR for forcing new image build with new cms
  jenkins-x.yml
Labels: approved, size/XS

#690 ENG-387 Add ConfirmUninstallModal to ComponentInstallActions
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/digital-exchange/components/common/ComponentInstallActions.js
  src/ui/digital-exchange/components/common/ComponentInstallActionsContainer.js
  src/ui/digital-exchange/components/common/ConfirmUninstallModal.js
Labels: approved, size/M

#688 ENG-158 await for delete and put only then
  src/state/page-config/actions.js
Labels: size/M

#682 ENG-141 re-enable hidden DE parts
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/digital-exchange/actions.js
  src/state/digital-exchange/categories/const.js
  src/state/digital-exchange/components/actions.js
  src/state/digital-exchange/components/reducer.js
  src/state/digital-exchange/components/types.js
  src/state/digital-exchange/extra-filters/actions.js
  src/ui/digital-exchange/CategoryFilter.js
  src/ui/digital-exchange/CategoryFilterContainer.js
  src/ui/digital-exchange/CategoryTabBarFilterContainer.js
  src/ui/digital-exchange/Sidebar.js
  src/ui/digital-exchange/components/list/ComponentList.js
  src/ui/digital-exchange/components/list/ComponentListContainer.js
  src/ui/digital-exchange/components/list/ComponentListPage.js
  test/state/digital-exchange/actions.test.js
  test/ui/digital-exchange/CategoryTabBarFilterContainer.test.js
  test/ui/digital-exchange/TabBarFilter.test.js
  test/ui/digital-exchange/components/list/ComponentListContainer.test.js
Labels: size/L

#692 ENG-388 Implement handling of DE component usage on uninstall
  src/api/digital-exchange/components.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/digital-exchange/components/actions.js
  src/state/digital-exchange/components/reducer.js
  src/state/digital-exchange/components/selectors.js
  src/state/digital-exchange/components/types.js
  src/ui/digital-exchange/components/common/ComponentInstallActions.js
  src/ui/digital-exchange/components/common/ComponentInstallActionsContainer.js
  src/ui/digital-exchange/components/common/ConfirmUninstallModal.js
  test/state/digital-exchange/components/actions.test.js
  test/state/digital-exchange/components/reducer.test.js
  test/state/digital-exchange/components/selectors.test.js
  test/test/mocks/digital-exchange/components.js
  test/ui/digital-exchange/components/common/ComponentInstallActionsContainer.test.js
Labels: size/L

#693 ENG-411 implement support for installation rollback
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/digital-exchange/components/actions.js
  src/state/digital-exchange/components/const.js
Labels: approved, size/S

#694 ENG-141 re-implement search with keyword
  src/state/digital-exchange/actions.js
  src/state/digital-exchange/categories/const.js
  src/state/digital-exchange/components/actions.js
Labels: size/M

#695 ENG-141 change search filter implementation
  package-lock.json
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/models/digital-exchange/components.js
  src/state/digital-exchange/actions.js
  src/state/digital-exchange/components/actions.js
  src/state/digital-exchange/components/reducer.js
  src/state/digital-exchange/components/selectors.js
  src/state/digital-exchange/components/types.js
  src/ui/common/form/FilterType.js
  src/ui/digital-exchange/components/FilterTypeContainer.js
  src/ui/digital-exchange/components/list/ComponentList.js
  src/ui/digital-exchange/components/list/ComponentListGridView.js
  src/ui/digital-exchange/components/list/ComponentListPage.js
  test/state/digital-exchange/actions.test.js
  test/state/digital-exchange/components/actions.test.js
  test/state/digital-exchange/components/reducer.test.js
  test/test/mocks/digital-exchange/components.js
Labels: size/L

#696 ENG-141 show hidden de
  sass/common/form/FilterType.scss
  sass/index.scss
  src/ui/common/form/FilterType.js
  src/ui/digital-exchange/components/list/ComponentListGridView.js
  src/ui/digital-exchange/components/list/ComponentListListView.js
  src/ui/digital-exchange/components/list/ComponentListPage.js
  test/ui/digital-exchange/components/list/ComponentListListView.test.js
Labels: approved, size/M

#697 ENG-409 apimanager patch version bump
  package-lock.json
  package.json
Labels: approved, size/S

#699 ENG-396 bump entando/menu version and pass dashboard link to menu
  package-lock.json
  package.json
  src/ui/internal-page/InternalPage.js
Labels: approved, size/M

#700 Create readme for keycloak and app-builder setup
  README.md
  with-keycloak.md
Labels: approved, size/M

#702 ENG-443 fix widget edit page not triggering
  src/ui/pages/config/DraggableWidgetFrame.js
  test/ui/pages/config/DraggableWidgetFrame.test.js
Labels: approved, size/S

#701 Keycloak doc
  with-keycloak.md
Labels: approved, size/XS

#698 ENG-398 implement toasts for errors
  src/state/activity-stream/actions.js
  src/state/categories/actions.js
  src/state/component-repository/categories/actions.js
  src/state/component-repository/component-repositories/actions.js
  src/state/component-repository/components/actions.js
  src/state/dashboard/actions.js
  src/state/data-models/actions.js
  src/state/data-types/actions.js
  src/state/database/actions.js
  src/state/file-browser/actions.js
  src/state/fragments/actions.js
  src/state/groups/actions.js
  src/state/labels/actions.js
  src/state/languages/actions.js
  src/state/page-config/actions.js
  src/state/page-templates/actions.js
  src/state/pages/actions.js
  src/state/permissions/actions.js
  src/state/profile-types/actions.js
  src/state/reload-configuration/actions.js
  src/state/users/actions.js
  src/state/widget-config/actions.js
  src/state/widgets/actions.js
  test/state/activity-stream/actions.test.js
  test/state/categories/actions.test.js
  test/state/component-repository/categories/actions.test.js
  test/state/component-repository/component-repositories/actions.test.js
  test/state/component-repository/components/actions.test.js
  test/state/dashboard/actions.test.js
  test/state/data-models/actions.test.js
  test/state/data-types/actions.test.js
  test/state/database/actions.test.js
  test/state/file-browser/actions.test.js
  test/state/fragments/actions.test.js
  test/state/groups/actions.test.js
  test/state/languages/actions.test.js
  test/state/page-config/actions.test.js
  test/state/page-templates/actions.test.js
  test/state/permissions/actions.test.js
  test/state/profile-types/actions.test.js
  test/state/reload-configuration/actions.test.js
  test/state/users/actions.test.js
  test/state/widget-config/actions.test.js
  test/state/widgets/actions.test.js
Labels: approved, size/L

#703 ENG-423 current user auth state reducer
  src/state/current-user-auth/actions.js
  src/state/current-user-auth/reducer.js
  src/state/current-user-auth/selectors.js
  src/state/current-user-auth/types.js
  src/state/rootReducer.js
  src/state/store.js
  test/state/current-user-auth/actions.test.js
  test/state/current-user-auth/reducer.test.js
  test/state/current-user-auth/selectors.test.js
Labels: approved, size/L
