Repository entando/app-builder, pull requests merged in 2020-11, with the labels that each got.

#895 ENG-1409 Use dynamic widget icon in WidgetFrame
  sass/pages/config/ContentWidgetElement.scss
  sass/pages/config/WidgetFrame.scss
  src/ui/pages/config/ContentWidgetElement.js
  src/ui/pages/config/WidgetFrame.js
  src/ui/pages/config/WidgetIcon.js
Labels: approved, size/M

#896 ENG-1408: When creating/editing a Page I should be see a thumbnail to select the Page Template
  public/images/1-2-column.svg
  public/images/1-2x2-1-column.svg
  public/images/1-2x4-1-column.svg
  public/images/1-column.svg
  public/images/custom-template.svg
  sass/index.scss
  sass/pages/common/FindTemplateModal.scss
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/pages/common/FindTemplateModal.js
  src/ui/pages/common/const.js
Labels: approved, size/L

#897 ENG-1408: fixing page template with thumbnails selection on edit mode
  sass/pages/common/FindTemplateModal.scss
  src/ui/pages/common/FindTemplateModal.js
  src/ui/pages/common/FindTemplateModalContainer.js
  src/ui/pages/common/PageForm.js
Labels: approved, size/S

#898 Eng 1418/table report dump
  sass/database/report/DatabaseDumpTablePage.scss
  sass/index.scss
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/app/App.js
  src/ui/database/dump/DatabaseDumpTablePage.js
  src/ui/database/dump/DatabaseDumpTablePageContainer.js
  src/ui/database/report/ReportDatabaseDataSource.js
  test/ui/database/dump/DatabaseDumpTablePage.test.js
  test/ui/database/dump/DatabaseDumpTablePageContainer.test.js
Labels: approved, size/M

#899 ENG-1375 fix incorrect payload naming
  src/state/profile-types/actions.js
  src/state/profile-types/selectors.js
  src/ui/profile-types/common/ProfileTypeReferenceStatus.js
  src/ui/profile-types/common/ProfileTypeReferenceStatusContainer.js
Labels: approved, size/S

#900 ENG-1418: adding conditions to prevent request being called multiple times
  src/ui/database/dump/DatabaseDumpTablePage.js
  src/ui/database/dump/DatabaseDumpTablePageContainer.js
  test/ui/database/dump/DatabaseDumpTablePageContainer.test.js
Labels: approved, size/S

#901 ENG-1404 update widget categories
  sass/index.scss
  sass/pages/config/ContentWidgetElement.scss
  sass/pages/config/WidgetFrame.scss
  sass/widgets/common/WidgetIcon.scss
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/widgets/selectors.js
  src/ui/pages/config/ContentWidgetElement.js
  src/ui/pages/config/WidgetFrame.js
  src/ui/widgets/common/WidgetIcon.js
  src/ui/widgets/list/WidgetListRow.js
Labels: approved, size/M

#902 Fix widget icon styles and remove unused styles
  sass/pages/config/ContentWidgetElement.scss
  sass/widgets/common/WidgetIcon.scss
  sass/widgets/list/WidgetListRow.scss
  src/ui/widgets/list/WidgetListRow.js
Labels: approved, size/M

#903 ENG-1358: ECR Repository list doesn't show bundle thumbnail
  src/ui/component-repository/components/item/ComponentImage.js
  test/ui/component-repository/components/item/ComponentImage.test.js
Labels: approved, size/XS

#904 ENG-1418: removing wrong condition
  src/ui/database/dump/DatabaseDumpTablePage.js
Labels: approved, size/XS

#905 ENG-1449 add a filter to remove null values from userReferences list
  src/ui/common/references/UserRefsTable.js
Labels: approved, size/XS

#907 ENG-1276 widget category support
  src/state/page-config/selectors.js
  src/state/widgets/selectors.js
  src/ui/common/section-collapse/SectionCollapse.js
  src/ui/pages/config/ContentWidget.js
  src/ui/pages/config/ContentWidgetContainer.js
  src/ui/widgets/list/ListWidgetPage.js
  src/ui/widgets/list/ListWidgetPageContainer.js
  test/state/page-config/selectors.test.js
  test/state/widgets/selectors.test.js
  test/ui/pages/config/ContentWidget.test.js
  test/ui/pages/config/ContentWidgetContainer.test.js
  test/ui/widgets/list/ListWidgetPage.test.js
  test/ui/widgets/list/ListWidgetPageContainer.test.js
Labels: approved, size/L

#906 ENG-1402 implement incremental name and code feature
  src/state/app-tour/actions.js
  src/state/app-tour/reducer.js
  src/state/app-tour/selectors.js
  src/state/app-tour/types.js
  src/state/pages/actions.js
  src/ui/pages/add/PagesAddFormContainer.js
  test/state/app-tour/actions.test.js
  test/state/app-tour/reducer.test.js
  test/state/app-tour/selectors.test.js
  test/ui/pages/add/PagesAddFormContainer.test.js
Labels: approved, size/L

#908 ENG-1276 fix regression on widget search
  src/state/page-config/selectors.js
  src/state/widgets/helpers.js
  src/state/widgets/selectors.js
  src/ui/pages/config/ContentWidgetContainer.js
Labels: approved, size/M

#909 Eng 1276 fix widget search issues + refactor
  package-lock.json
  package.json
  sass/common/CollapsibleSectionTitle.scss
  sass/index.scss
  sass/pages/config/WidgetGrouping.scss
  sass/pages/config/WidgetGroupingItem.scss
  sass/pages/config/WidgetGroupings.scss
  src/state/page-templates/selectors.js
  src/state/widget-config/selectors.js
  src/ui/common/CollapsibleSectionTitle.js
  src/ui/pages/config/ContentWidget.js
  src/ui/pages/config/DraggableContentWidgetElement.js
  src/ui/pages/config/ToolbarPageConfig.js
  src/ui/pages/config/WidgetGrouping.js
  src/ui/pages/config/WidgetGroupingDraggableItem.js
  src/ui/pages/config/WidgetGroupingItem.js
  src/ui/pages/config/WidgetGroupings.js
  src/ui/pages/config/WidgetGroupingsContainer.js
  test/ui/pages/config/ContentWidget.test.js
  test/ui/pages/config/WidgetGroupingItem.test.js
  test/ui/pages/config/WidgetGroupings.test.js
  test/ui/pages/config/WidgetGroupingsContainer.test.js
  test/ui/users/my-profile/AppSettingsForm.test.js
Labels: approved, size/XL

#910 ENG-1481 keep widget category when editing a widget
  src/state/widgets/actions.js
  src/ui/widgets/common/WidgetForm.js
Labels: approved, size/XS

#911 ENG-1402 add Icon for the new Widget NWS_Search_Results
  src/ui/widgets/common/WidgetIcon.js
Labels: approved, size/XS

#913 ENG-1432 Fix LabelsTable cell word break
  sass/labels/list/LabelsTable.scss
  src/ui/labels/list/LabelsTable.js
Labels: approved, size/M

#914 ENG-1475 Add and use fallback page titles
  src/state/pages/selectors.js
  src/ui/pages/common/PageInfoTable.js
  src/ui/pages/config/PageConfigPageContainer.js
  test/state/pages/selectors.test.js
  test/ui/pages/common/PageTreeSelectorContainer.test.js
  test/ui/pages/config/PageConfigPageContainer.test.js
  test/ui/widgets/edit/EditWidgetFormContainer.test.js
Labels: approved, size/S

#912 ENG-1444: Improve the layout of the ECR by adopting the new wireframe
  sass/common/form/SearchForm.scss
  sass/component-repository/common/SidebarFilter.scss
  sass/component-repository/common/TabBarFilter.scss
  sass/component-repository/components/ComponentList.scss
  sass/component-repository/components/ComponentListPage.scss
  sass/index.scss
  sass/patternfly.scss
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/common/form/SearchForm.js
  src/ui/component-repository/common/TabBarFilter.js
  src/ui/component-repository/components/list/ComponentList.js
  src/ui/component-repository/components/list/ComponentListGridView.js
  src/ui/component-repository/components/list/ComponentListListView.js
  src/ui/component-repository/components/list/ComponentListPage.js
  src/ui/component-repository/components/list/ComponentListViewModeSwitcherContainer.js
  test/ui/component-repository/components/list/ComponentListGridView.test.js
Labels: approved, size/L

#915 Eng 1493 widget ux fixes
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
  src/ui/widgets/common/WidgetForm.js
  test/ui/widgets/common/WidgetForm.test.js
Labels: approved, size/S

#916 ENG-1402 preconfigured widgets
  src/locales/en.js
  src/locales/it.js
  src/ui/app-tour/AppTour.js
  src/ui/app-tour/AppTourContainer.js
  src/ui/pages/add/PagesAddFormContainer.js
  src/ui/pages/common/PageForm.js
  src/ui/pages/common/PageTreeSelectorContainer.js
  src/ui/pages/config/PageConfigPage.js
  test/ui/app-tour/AppTour.test.js
  test/ui/pages/add/PagesAddFormContainer.test.js
Labels: approved, size/L

#919 ENG-1467 realign labels + re-placing breadcrumbs on widgets page
  src/locales/en.js
  src/ui/widgets/list/ListWidgetPage.js
Labels: approved, size/S

#918 ENG-1402 remove news search results widget icon
  src/ui/widgets/common/WidgetIcon.js
Labels: approved, size/XS

#920 ENG-1467 menu label change on widget menu item
  src/locales/en.js
  src/locales/it.js
Labels: approved, size/XS

#917 ENG-1444: applying changes agreed in the review meeting
  sass/component-repository/components/ComponentList.scss
  src/api/component-repository/components.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/component-repository/components/item/install-controls/UninstallButton.js
  src/ui/component-repository/components/list/ComponentList.js
  src/ui/component-repository/components/list/ComponentListGridView.js
  src/ui/component-repository/components/list/ComponentListListView.js
  test/ui/component-repository/components/list/ComponentListGridView.test.js
Labels: approved, size/L

#921 ENG-1467 All Microfrontend labels changed
  src/locales/en.js
  src/locales/it.js
Labels: approved, size/S

#922 ENG-1444: removing mock request
  src/api/component-repository/components.js
Labels: approved, size/XS

#923 ENG-1501 internal servlet widget config fix
  src/helpers/getAppBuilderWidgetForm.js
  src/ui/widgets/config/WidgetConfigPage.js
  src/ui/widgets/config/forms/SimpleWidgetConfigForm.js
  src/ui/widgets/config/forms/SimpleWidgetConfigFormContainer.js
Labels: approved, size/L

#924 ENG-1402 change tutorial to align with new UX
  src/locales/en.js
  src/state/pages/actions.js
  src/ui/app-tour/AppTour.js
  src/ui/app-tour/AppTourContainer.js
  src/ui/pages/add/PagesAddFormContainer.js
  src/ui/pages/list/PageTreePage.js
  src/ui/pages/list/PageTreePageContainer.js
  test/ui/app-tour/AppTour.test.js
  test/ui/pages/list/PageTreePageContainer.test.js
Labels: approved, size/M

#925 ENG-1428: In Categories page, Expand All and Collapse All are missing
  sass/categories/list/CategoryTree.scss
  src/state/categories/actions.js
  src/state/categories/reducer.js
  src/ui/categories/list/CategoryTree.js
  src/ui/categories/list/CategoryTreeContainer.js
Labels: approved, size/L

#926 ENG-1478 Amend breadcrumbs
  src/ui/categories/add/AddCategoryPage.js
  src/ui/categories/detail/DetailCategoryPage.js
  src/ui/categories/edit/EditCategoryPage.js
  src/ui/categories/list/ListCategoryPage.js
  src/ui/database/add/AddDatabasePage.js
  src/ui/database/list/ListDatabasePage.js
  src/ui/database/report/ReportDatabasePage.js
  src/ui/file-browser/add/CreateFolderPage.js
  src/ui/file-browser/add/CreateTextFilePage.js
  src/ui/file-browser/edit/EditTextFilePage.js
  src/ui/file-browser/list/ListFilesPage.js
  src/ui/file-browser/upload/UploadFileBrowserPage.js
  src/ui/labels/list/LabelsAndLanguagesPage.js
  src/ui/page-templates/list/PageTemplateListPage.js
Labels: approved, size/S

#927 ENG-1375 implement new assignedRoles + allowedRoles
  src/api/profileTypes.js
  src/state/profile-types/actions.js
  src/state/profile-types/selectors.js
  src/ui/common/attributes/AttributeRole.js
  src/ui/common/form/RoleSelectRenderer.js
  src/ui/profile-types/attributes/AddFormContainer.js
  src/ui/profile-types/attributes/EditFormContainer.js
  src/ui/profile-types/edit/EditFormContainer.js
  test/api/profileTypes.test.js
Labels: approved, size/M

#928 ENG-1508 Fix category deletion not properly updating children map
  src/state/categories/actions.js
  src/state/categories/reducer.js
  src/ui/categories/common/DeleteCategoryModal.js
  src/ui/categories/common/DeleteCategoryModalContainer.js
  src/ui/categories/list/CategoryTree.js
  src/ui/categories/list/CategoryTreeContainer.js
  test/state/categories/reducer.test.js
Labels: approved, size/M

#929 ENG-1478 Amend breadcrumbs
  src/ui/reload-configuration/ReloadConfigPage.js
  src/ui/reload-configuration/ReloadConfirmPage.js
Labels: approved, size/XS

#930 ENG-1402 change navbar and content list configs
  src/ui/app-tour/AppTourContainer.js
Labels: approved, size/XS

#931 ENG-1375 bump frontend libraries with new FE email regex
  package-lock.json
  package.json
Labels: approved, size/S

#932 ENG-1402 fix QE feedback
  src/auth/keycloak/KeycloakProviderContainer.js
  src/ui/app-tour/AppTour.js
  src/ui/app-tour/AppTourContainer.js
  src/ui/pages/add/PagesAddFormContainer.js
  src/ui/pages/common/PageForm.js
  src/ui/pages/config/PageConfigPageContainer.js
Labels: approved, size/S

#933 ENG-1402 update Italian texts
  src/locales/it.js
Labels: approved, size/XS

#934 ENG-1495 functionality on re-adding removed roles to role dropdown (profile types)
  src/state/profile-types/selectors.js
  src/ui/profile-types/attributes/AddFormContainer.js
  src/ui/profile-types/attributes/EditFormContainer.js
Labels: approved, size/M

#935 ENG-1518 Use formatted messages as labels in my profile page
  src/ui/users/my-profile/MyProfileEditForm.js
  src/ui/users/my-profile/MyProfilePage.js
  test/ui/users/my-profile/MyProfilePage.test.js
Labels: approved, size/M

#937 ENG-1495 issue on all roles that are already assigned (profile types)
  src/ui/common/attributes/AttributeRole.js
  src/ui/common/form/RoleSelectRenderer.js
Labels: approved, size/M

#938 Refactor usage of homepage code by defining it as a constant
  src/state/pages/actions.js
  src/state/pages/const.js
  src/state/pages/selectors.js
  src/ui/internal-page/BrandMenuContainer.js
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
  src/ui/widgets/config/forms/NavigationBarConfigFormContainer.js
  test/state/page-config/actions.test.js
  test/state/page-config/selectors.test.js
  test/state/pages/actions.test.js
  test/state/pages/reducer.test.js
Labels: approved, size/M

#939 ENG-1522 re-render the PageSettings form on page select
  src/ui/pages/config/PageConfigPage.js
  test/ui/pages/config/PageConfigPage.test.js
Labels: approved, size/M

#940 ENG-1526: UX Fragments - pagination doesn’t work correctly after filtering the list via search
  src/state/fragments/actions.js
  src/state/fragments/reducer.js
  src/state/fragments/selectors.js
  src/state/fragments/types.js
  src/ui/fragments/list/FragmentListTable.js
  src/ui/fragments/list/FragmentListTableContainer.js
  src/ui/fragments/list/FragmentSearchFormContainer.js
  test/state/fragments/actions.test.js
  test/state/fragments/reducer.test.js
  test/state/fragments/selectors.test.js
  test/test/mocks/fragments.js
  test/ui/fragments/list/FragmentSearchFormContainer.test.js
Labels: approved, size/M

#942 ENG-1509 resolve issue on SEO metatag items and form
  src/ui/pages/common/PageForm.js
  src/ui/pages/common/SeoInfo.js
  src/ui/pages/common/SeoInfoMetadataContainer.js
  src/ui/pages/common/SeoMetadataForm.js
Labels: approved, size/L

#943 ENG-1526: changing initial state to be a string
  src/state/fragments/reducer.js
Labels: approved, size/XS

#944 ENG-1523 implement new approach for handling save page settings
  __mocks__/redux-form.js
  src/ui/pages/common/PageForm.js
  src/ui/pages/config/PageConfigPage.js
  src/ui/pages/config/PageConfigPageContainer.js
  src/ui/pages/edit/PagesEditFormContainer.js
Labels: approved, size/M

#946 Update prop-types version
  package-lock.json
  package.json
Labels: approved, size/S

#945 ENG-1524 Fix page settings form not resetting metatag fields
  __mocks__/redux-form.js
  src/ui/pages/config/PageConfigPageContainer.js
  test/ui/pages/config/PageConfigPageContainer.test.js
Labels: approved, size/M

#947 ENG-1531 resolve cosmetic issues
  sass/internal-page/InternalPage.scss
  sass/widgets/common/WidgetForm.scss
  src/locales/en.js
  src/ui/pages/common/PageSettingsForm.js
  src/ui/pages/list/PageSearchForm.js
  src/ui/widgets/common/WidgetForm.js
  test/ui/pages/common/PageSettingsForm.test.js
Labels: approved, size/L

#948 ENG-1542 swap last two tutorial steps
  src/locales/en.js
  src/locales/it.js
  src/ui/app-tour/AppTour.js
  src/ui/app-tour/AppTourContainer.js
  src/ui/pages/config/PageConfigPage.js
  src/ui/pages/config/PageConfigPageContainer.js
  test/ui/app-tour/AppTour.test.js
Labels: approved, size/M

#949 ENG-1480 remove a warning
  src/ui/internal-page/InfoMenu.js
Labels: approved, size/XS

#950 ENG-1543 Fix ecr install/uninstall loading on error
  src/state/component-repository/components/actions.js
  test/state/component-repository/components/actions.test.js
Labels: approved, size/M

#951 ENG-1539: Page Designer: the restore button doesn't work on page reload
  src/state/page-config/actions.js
  test/state/page-config/actions.test.js
Labels: approved, size/S

#953 Add button alignment to dropdown - multiselect field component
  sass/pages/common/MultiSelectRenderer.scss
Labels: approved, size/XS

#952 ENG-1531 format of default UI field (newlines/tabspaces) in widget form
  sass/widgets/common/WidgetForm.scss
  src/ui/widgets/common/WidgetForm.js
Labels: approved, size/S

#954 ENG-1549 Fix ecr component button styling
  sass/component-repository/components/ComponentList.scss
  src/ui/component-repository/components/list/ComponentListGridView.js
Labels: approved, size/M

#955 ENG-1554 Fix page config fetching logic
  src/state/page-config/actions.js
Labels: approved, size/S

#956 ENG-1559 Fix component list page styling if side nav is collapsed
  sass/component-repository/components/ComponentListPage.scss
Labels: approved, size/XS
