Repository entando/app-builder, pull requests merged in 2021-01, with the labels that each got.

#973 ENG-1593 disable body scroll lock for mobile devices
  src/ui/app-tour/AppTour.js
Labels: approved, size/XS

#974 Update README.md
  README.md
Labels: approved, size/XS

#975 ENG-1593 Increase scroll lock threshold
  src/ui/app-tour/AppTour.js
Labels: approved, size/XS

#978 ENG-1086 ENG-1082 ENG-1106 remove API Managment from App Builder
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: approved, size/S

#979 ENG-1747: unformatted page position in the page tree after cloning or adding new additional pages
  sass/pages/common/PageTreeCompact.scss
  src/ui/pages/common/PageTreeCompact.js
  src/ui/pages/edit/PagesEditFormContainer.js
  test/ui/pages/edit/PagesEditFormContainer.test.js
Labels: approved, size/M

#980 increase polling and timeout interval
  src/helpers/pollApi.js
Labels: approved, size/XS

#981 ENG-1096 remove content scheduler option from app builder
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: approved, size/S

#976 ENG-1709 update to ubi based dockerfile
  Dockerfile
  licenses/licenses.csv
Labels: approved, size/XXL
