Repository entando/app-builder, pull requests merged in 2021-04, with the labels that each got.

#1038 ENG-2039: Create ECR Access permission
  src/state/permissions/const.js
  src/ui/component-repository/components/list/ComponentListPage.js
  src/ui/internal-page/BrandMenuContainer.js
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
Labels: approved, size/S

#1037 Add page management commands
  package-lock.json
  src/ui/pages/common/PageTreeActionMenu.js
  src/ui/test-const/page-management-test-const.js
  test/cypress/integration/pages-management.spec.js
  test/cypress/support/command/command.js
  test/cypress/support/command/page-management-command.js
  test/cypress/support/index.js
Labels: approved, size/L

#1028 Update app builder build for security scans
  Dockerfile
Labels: approved, size/XS

#1041 Eng 2151 add upload file for cypress
  package-lock.json
  package.json
  src/ui/test-const/admin-test-const.js
  src/ui/test-const/components-test-const.js
  test/cypress/fixtures/icon/Entando.svg
  test/cypress/fixtures/upload/data1.json
  test/cypress/fixtures/upload/data2.json
  test/cypress/fixtures/upload/data3.json
  test/cypress/fixtures/upload/data4.json
  test/cypress/integration/administration.spec.js
  test/cypress/integration/components.spec.js
  test/cypress/support/command/upload-command.js
  test/cypress/support/index.js
Labels: approved, size/L

#1044 ENG-1827: profile picture
  package-lock.json
  package.json
  public/images/user-edit.svg
  public/images/user-icon.svg
  sass/index.scss
  sass/users/common/ProfileImageUploader.scss
  sass/users/my-profile/MyProfilePage.scss
  src/helpers/resourcePath.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/file-browser/actions.js
  src/state/forms/selectors.js
  src/state/user-profile/selectors.js
  src/ui/users/common/ProfileImageUploader.js
  src/ui/users/my-profile/MyProfileEditForm.js
  src/ui/users/my-profile/MyProfileEditFormContainer.js
  src/ui/users/my-profile/MyProfilePage.js
Labels: approved, size/L

#1043 ENG-2071 cypress commands improvements
  package-lock.json
  package.json
  src/ui/common/modal/GenericModal.js
  src/ui/pages/common/PageTreeActionMenu.js
  src/ui/pages/config/EmptyFrame.js
  src/ui/pages/config/WidgetFrame.js
  src/ui/roles/list/RoleListTable.js
  src/ui/test-const/admin-test-const.js
  src/ui/test-const/components-test-const.js
  src/ui/test-const/page-designer-test-const.js
  src/ui/test-const/page-management-test-const.js
  src/ui/test-const/role-test-const.js
  src/ui/test-const/test-const.js
  src/ui/test-const/user-test-const.js
  src/ui/users/common/AddAuthorityModal.js
  src/ui/users/list/UserListTable.js
  test/cypress/fixtures/icon/Entando.svg
  test/cypress/fixtures/upload/data1.json
  test/cypress/fixtures/upload/data2.json
  test/cypress/fixtures/upload/data3.json
  test/cypress/fixtures/upload/data4.json
  test/cypress/integration/administration.spec.js
  test/cypress/integration/components.spec.js
  test/cypress/integration/pages-designer.spec.js
  test/cypress/integration/pages-management.spec.js
  test/cypress/integration/users-management-ui.spec.js
  test/cypress/integration/users-management.spec.js
  test/cypress/integration/users-roles-ui.spec.js
  test/cypress/integration/users-roles.spec.js
  test/cypress/support/command/command.js
  test/cypress/support/command/page-designer-command.js
  test/cypress/support/command/page-management-command.js
  test/cypress/support/command/role-command.js
  test/cypress/support/command/upload-command.js
  test/cypress/support/command/user-command.js
  test/cypress/support/index.js
Labels: approved, size/XL

#1042 ENG-2116: In app-builder add a babel plugin to remove the data-testid in production build
  package-lock.json
  package.json
Labels: approved, size/S

#1045 ENG-2176 add potential patch to fragments blank page
  src/ui/fragments/list/FragmentListTable.js
  src/ui/fragments/list/FragmentSearchForm.js
  src/ui/fragments/list/ListFragmentPage.js
Labels: approved, size/XS

#1046 update base nginx ubi image in dockerfile
  Dockerfile
Labels: approved, size/XS

#1047 ENG-2219 show all groups when adding a new page as admin
  src/state/groups/actions.js
  src/state/groups/selectors.js
  test/state/groups/actions.test.js
  test/state/groups/selectors.test.js
Labels: approved, size/M

#1048 ENG-2222 filter groups for non-admins in page edit screen
  src/ui/pages/edit/PagesEditFormContainer.js
  test/ui/pages/edit/PagesEditFormContainer.test.js
Labels: approved, size/M

#1049 ENG-2229: fixing image upload issue
  sass/users/common/ProfileImageUploader.scss
  src/state/file-browser/actions.js
Labels: approved, size/M

#1050 ENG-2009: ensuring we will send 'latest' version if none was specified
  src/state/component-repository/components/actions.js
  src/state/component-repository/components/reducer.js
Labels: approved, size/XS

#1051 ENG-2245 menu cleanup
  __mocks__/@entando/menu.js
  config/env.js
  docker-entrypoint.sh
  jenkins-x.yml
  sass/internal-page/InternalPage.scss
  sass/patternfly.scss
  src/helpers/getRuntimeEnv.js
  src/ui/internal-page/BrandMenuContainer.js
  src/ui/internal-page/InternalPage.js
  src/ui/internal-page/LanguageSelect.js
  src/ui/internal-page/VerticalMenuContainer.js
Labels: approved, size/L

#1054 ENG-2177 fix tutorial slow display navigatable
  src/ui/app-tour/AppTour.js
Labels: approved, size/XS

#1036 ENG-2070 Add cypress tests for groups
  src/ui/groups/common/GroupForm.js
  src/ui/groups/list/GroupListMenuActions.js
  src/ui/groups/list/GroupListTable.js
  src/ui/groups/list/ListGroupPage.js
  src/ui/test-const/group-test-const.js
  test/cypress/integration/groups.spec.js
  test/cypress/support/command/group-command.js
  test/cypress/support/index.js
Labels: approved, size/M

#1057 ENG-2177 revert change
  src/ui/app-tour/AppTour.js
Labels: approved, size/XS

#1053 ENG-2180 cypress test for complex content types
  src/ui/test-const/content-types-const.js
  test/cypress/integration/content-types.spec.js
  test/cypress/support/command/command.js
  test/cypress/support/command/content-types-command.js
  test/cypress/support/index.js
Labels: approved, size/L

#1055 ENG-2009: do not check for install plan if it is already resolved
  src/state/component-repository/components/actions.js
Labels: approved, size/M

#1056 ENG-2192 Add page full path to page search results
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/pages/list/PageListSearchTable.js
Labels: approved, size/S

#1052 ENG-2175 Pages management tests added and other improvements
  src/ui/common/form/RenderDropdownTypeaheadInput.js
  src/ui/groups/list/GroupListTable.js
  src/ui/pages/common/PageForm.js
  src/ui/test-const/page-management-test-const.js
  test/cypress/integration/administration-file-browser.spec.js
  test/cypress/integration/components-micro-frontends-and-widgets.spec.js
  test/cypress/integration/pages-designer.spec.js
  test/cypress/integration/pages-management.spec.js
  test/cypress/integration/users-groups.spec.js
  test/cypress/integration/users-management-ui.spec.js
  test/cypress/integration/users-management.spec.js
  test/cypress/integration/users-roles-ui.spec.js
  test/cypress/mocks/pages.js
  test/cypress/support/command/command.js
  test/cypress/support/command/group-command.js
  test/cypress/support/command/page-command.js
  test/cypress/support/command/page-designer-command.js
  test/cypress/support/command/page-management-command.js
  test/cypress/support/command/role-command.js
  test/cypress/support/command/user-command.js
  test/cypress/support/index.js
  test/cypress/support/utils.js
Labels: approved, size/XL

#1058 ENG-2146 test basic content type attributes
  test/cypress/integration/content-type-attributes.spec.js
  test/cypress/support/command/command.js
Labels: approved, size/M

#1059 ENG-2190 consistent process on expanding tree directories for both category and page tree
  src/state/app-tour/const.js
  src/state/categories/actions.js
  src/state/categories/reducer.js
  src/state/categories/types.js
  src/state/pages/actions.js
  src/state/pages/reducer.js
  src/state/pages/types.js
  src/ui/app-tour/AppTourContainer.js
  src/ui/pages/add/PagesAddFormContainer.js
  src/ui/pages/list/PageTreePageContainer.js
  test/state/categories/actions.test.js
  test/state/categories/reducer.test.js
  test/state/pages/actions.test.js
  test/state/pages/reducer.test.js
Labels: approved, size/L

#1061 ENG-2191 amend async fetch on all levels of page/category tree branches
  src/state/categories/actions.js
  src/state/categories/selectors.js
  src/state/pages/actions.js
  src/state/pages/selectors.js
  test/state/categories/actions.test.js
Labels: approved, size/M

#1062 ENG-2177 fix tutorial
  src/auth/keycloak/KeycloakProviderContainer.js
  src/state/app-tour/reducer.js
  src/ui/common/form/RenderDropdownTypeaheadInput.js
  test/state/app-tour/reducer.test.js
Labels: approved, size/S

#1060 ENG-2082: cleaning up warnings on jest
  config/output.js
  package.json
  src/ui/fragments/list/FragmentListTable.js
  src/ui/fragments/list/ListFragmentPage.js
Labels: approved, size/M
