Repository entando/app-builder, pull requests merged in 2021-09, with the labels that each got.

#1115 ENG-2223 join group options for page form now shows all group entries
  src/ui/pages/add/PagesAddFormContainer.js
  src/ui/pages/common/PageForm.js
  src/ui/pages/edit/PagesEditFormContainer.js
  test/ui/pages/add/PagesAddFormContainer.test.js
  test/ui/pages/common/PageForm.test.js
  test/ui/pages/edit/PagesEditFormContainer.test.js
Labels: approved, size/M

#1117 ENG-2603 update entando version
  Dockerfile
  package-lock.json
  package.json
Labels: size/S

#1116 ENG-2599: adding test to owner group field
  test/ui/pages/common/PageForm.test.js
Labels: approved, size/S

#1120 ENG-2452 Update owners
  OWNERS_ALIASES
Labels: approved, size/S

#1118 ENG-2368: adding visual response when API request fails
  src/state/component-repository/components/actions.js
Labels: approved, size/XS

#1119 ENG-2611: adding downgrade confirmation modal
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/component-repository/components/item/install-controls/ComponentInstallActions.js
  src/ui/component-repository/components/item/install-controls/ConfirmDowngradeModal.js
Labels: approved, size/M

#1121 ECS-110 remove cms redux persistance
  src/state/store.js
  test/state/store.test.js
Labels: approved, size/M

#1122 ENG-2611: adding handler for versions without 'v' as prefix
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/component-repository/components/item/install-controls/ComponentInstallActions.js
  src/ui/component-repository/components/item/install-controls/ConfirmDowngradeModal.js
Labels: approved, size/M
