Repository entando/app-builder, pull requests merged in 2021-02, with the labels that each got.

#983 React router and enzyme update
  package-lock.json
  package.json
  test/ui/activity-stream/NotificationList.test.js
  test/ui/labels/common/LabelsForm.test.js
  test/ui/pages/add/PageSearchForm.test.js
  test/ui/pages/common/PageStatusIcon.test.js
  test/ui/plugins/PluginsPage.test.js
Labels: approved, size/XXL

#984 ENG-1767 implement save and continue dropdown feature for fragments add/edit
  sass/fragment/FragmentForm.scss
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/fragments/actions.js
  src/state/fragments/const.js
  src/ui/fragments/add/AddFormContainer.js
  src/ui/fragments/common/FragmentForm.js
  src/ui/fragments/edit/EditFormContainer.js
  test/state/fragments/actions.test.js
  test/ui/fragments/common/FragmentForm.test.js
Labels: approved, size/L

#985 ENG-1768 implement save and continue functionality for add/edit widget
  src/state/fragments/actions.js
  src/state/widgets/actions.js
  src/state/widgets/const.js
  src/ui/widgets/clone/CloneWidgetFormContainer.js
  src/ui/widgets/common/WidgetForm.js
  src/ui/widgets/common/WidgetFormContainer.js
  src/ui/widgets/edit/EditWidgetFormContainer.js
  src/ui/widgets/newUserWidget/NewUserWidgetFormContainer.js
  test/state/fragments/actions.test.js
  test/state/widgets/actions.test.js
  test/ui/widgets/common/WidgetForm.test.js
Labels: approved, size/L

#986 ENG-1769 implement save and continue functionality for page templates
  src/state/page-templates/actions.js
  src/state/page-templates/const.js
  src/ui/page-templates/common/PageTemplateForm.js
  src/ui/page-templates/common/PageTemplateFormContainer.js
  test/state/page-templates/actions.test.js
  test/ui/page-templates/common/PageTemplateForm.test.js
  test/ui/page-templates/common/PageTemplateFormContainer.test.js
Labels: approved, size/L

#988 ENG-1464 widget view toggle functionality
  sass/index.scss
  sass/pages/config/WidgetGroupingListItem.scss
  sass/pages/config/WidgetGroupings.scss
  src/ui/pages/config/WidgetGrouping.js
  src/ui/pages/config/WidgetGroupingDraggableListItem.js
  src/ui/pages/config/WidgetGroupingListItem.js
  src/ui/pages/config/WidgetGroupings.js
Labels: approved, size/L

#989 Update with-keycloak.md
  with-keycloak.md
Labels: approved, size/XS

#990 Update with-keycloak.md
  with-keycloak.md
Labels: approved, size/XS

#991 ENG-1679 Add cypress testing to app-builder
  .eslintrc.js
  cypress.json
  package-lock.json
  package.json
  src/ui/common/form/RenderTextInput.js
  src/ui/internal-page/PageTitle.js
  src/ui/pages/add/PagesAddPage.js
  src/ui/pages/common/PageForm.js
  src/ui/pages/common/SeoInfo.js
  src/ui/pages/list/PageTreePage.js
  src/ui/roles/add/AddRolePage.js
  src/ui/roles/common/RoleForm.js
  src/ui/roles/edit/EditRolePage.js
  src/ui/roles/list/ListRolePage.js
  src/ui/users/add/AddUserPage.js
  test/cypress/fixtures/users/user.json
  test/cypress/integration/pages.spec.js
  test/cypress/integration/roles.spec.js
  test/cypress/plugins/index.js
  test/cypress/support/command.js
  test/cypress/support/exception-handler.js
  test/cypress/support/index.js
  test/cypress/support/keycloak-oauth2.js
  test/cypress/support/utils.js
Labels: approved, size/XXL

#992 ENG-1709 parameterized version label
  Dockerfile
  jenkins-x.yml
  skaffold.yaml
Labels: approved, size/S

#994 ENG-1639 fix undefined latest version access
  src/ui/component-repository/components/list/ComponentListGridView.js
  src/ui/component-repository/components/list/ComponentListListView.js
Labels: approved, size/XS

#995 reverting ENG-1482
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/user-preferences/reducer.js
  src/ui/users/my-profile/AppSettingsForm.js
  test/test/mocks/userPreferences.js
Labels: approved, size/S

#996 ENG-1639 fix install version
  src/ui/component-repository/components/item/install-controls/ComponentInstallActions.js
Labels: approved, size/XS

#997 ENG-1770 amend dropdown typeahead field component for group fields
  package-lock.json
  package.json
  sass/common/form/DropdownTypeahead.scss
  sass/index.scss
  sass/patternfly.scss
  src/locales/en.js
  src/locales/it.js
  src/ui/common/form/RenderDropdownTypeaheadInput.js
  src/ui/pages/add/PagesAddFormContainer.js
  src/ui/pages/common/PageForm.js
  src/ui/pages/edit/PagesEditFormContainer.js
  test/ui/pages/edit/PagesEditFormContainer.test.js
Labels: approved, size/L

#998 ENG-1688 Implement Default Page Owner Group and Join Groups
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/user-preferences/reducer.js
  src/state/users/actions.js
  src/state/users/reducer.js
  src/state/users/selectors.js
  src/ui/common/form/RenderSelectInput.js
  src/ui/common/form/SwitchRenderer.js
  src/ui/pages/add/PagesAddFormContainer.js
  src/ui/pages/common/MultiSelectRenderer.js
  src/ui/users/my-profile/AppSettingsForm.js
  src/ui/users/my-profile/AppSettingsFormContainer.js
  test/ui/pages/add/PagesAddFormContainer.test.js
  test/ui/users/my-profile/AppSettingsForm.test.js
Labels: approved, size/L

#1000 ENG-1771 implement pages search by name
  sass/index.scss
  sass/pages/list/PageSearchForm.scss
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/pages/list/PageSearchForm.js
  src/ui/pages/list/PageTreePageContainer.js
  test/ui/pages/add/PageSearchForm.test.js
Labels: approved, size/L

#1001 ENG-1510 implement multi language friendly code for app-builder
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/pages/common/PageForm.js
  src/ui/pages/common/SeoInfo.js
  src/ui/pages/common/const.js
  test/ui/pages/add/PagesAddFormContainer.test.js
Labels: approved, size/M

#1003 Update react-redux and react-test-renderer to latest compatible versions
  package-lock.json
  package.json
Labels: approved, size/L

#1002 ENG-1828 replace TextArea component with RTE for customUI field
  package-lock.json
  package.json
  sass/common/form/RenderRichTextEditor.scss
  sass/index.scss
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/common/form/RenderRichTextEditor.js
  src/ui/common/rich-text-editor/EditorToolbar.js
  src/ui/common/rich-text-editor/RichTextEditor.js
  src/ui/common/rich-text-editor/SpecialCharSelectorModal.js
  src/ui/widgets/common/WidgetForm.js
Labels: approved, size/XXL

#1005 ENG-1828 implement link/unlink modal in RTE
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/common/link-config/LinkConfigAttributes.js
  src/ui/common/link-config/LinkConfigUrlForm.js
  src/ui/common/modal/LinkConfigModal.js
  src/ui/common/rich-text-editor/RichTextEditor.js
  src/ui/common/rich-text-editor/SpecialCharSelectorModal.js
Labels: approved, size/L

#1004 ENG-1842 fix help text for new username
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
Labels: approved, size/XS

#1006 ENG-1880 Change max username character length to 80
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/users/common/UserForm.js
  test/ui/users/common/UserForm.test.js
Labels: approved, size/S

#1007 ENG-1102 implement cancel buttons and confirm modals
  sass/users/common/UserForm.scss
  src/ui/groups/add/AddFormContainer.js
  src/ui/groups/common/GroupForm.js
  src/ui/groups/edit/EditFormContainer.js
  src/ui/page-templates/common/PageTemplateForm.js
  src/ui/page-templates/common/PageTemplateFormContainer.js
  src/ui/profile-types/add/AddFormContainer.js
  src/ui/profile-types/common/ProfileTypeForm.js
  src/ui/profile-types/edit/EditFormContainer.js
  src/ui/roles/add/AddFormContainer.js
  src/ui/roles/common/RoleForm.js
  src/ui/roles/edit/EditFormContainer.js
  src/ui/users/add/AddFormContainer.js
  src/ui/users/common/UserForm.js
  src/ui/users/edit/EditFormContainer.js
  test/ui/groups/add/AddFormContainer.test.js
  test/ui/groups/common/GroupForm.test.js
  test/ui/groups/edit/EditFormContainer.test.js
  test/ui/roles/add/AddFormContainer.test.js
  test/ui/roles/common/RoleForm.test.js
  test/ui/roles/edit/EditFormContainer.test.js
  test/ui/users/edit/EditFormContainer.test.js
Labels: approved, size/L

#1008 ENG-1461: Integrating widgets to use custom icons
  package-lock.json
  package.json
  sass/index.scss
  sass/pages/config/WidgetGroupingItem.scss
  sass/widgets/common/IconLibrary.scss
  sass/widgets/common/IconUploader.scss
  sass/widgets/common/WidgetIcon.scss
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/file-browser/actions.js
  src/state/widgets/actions.js
  src/state/widgets/selectors.js
  src/ui/widgets/common/IconLibrary.js
  src/ui/widgets/common/IconUploader.js
  src/ui/widgets/common/WidgetForm.js
  src/ui/widgets/common/WidgetIcon.js
  test/state/fragments/actions.test.js
  test/state/widgets/actions.test.js
  test/state/widgets/selectors.test.js
  test/test/mocks/fontAwesomeIcons.js
  test/test/mocks/widgets.js
  test/test/testUtils.js
  test/ui/pages/config/WidgetGroupings.test.js
  test/ui/widgets/common/IconUploader.test.js
  test/ui/widgets/common/WidgetIcon.test.js
Labels: approved, size/XXL

#1009 ENG-1882 implement typeahead for MFE/widget screen groups field
  package-lock.json
  src/ui/widgets/common/WidgetForm.js
Labels: approved, size/M

#1010 ENG-1461: adding fallback icon and helpText
  public/images/puzzle-piece-solid.svg
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/widgets/common/WidgetForm.js
  src/ui/widgets/common/WidgetIcon.js
Labels: approved, size/S

#1011 ENG-1883 implement default group for widget adding
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/users/my-profile/AppSettingsForm.js
  src/ui/users/my-profile/AppSettingsFormContainer.js
  src/ui/widgets/common/WidgetForm.js
  src/ui/widgets/common/WidgetFormContainer.js
  src/ui/widgets/common/WidgetIcon.js
  test/ui/widgets/common/WidgetFormContainer.test.js
Labels: approved, size/M

#1013 ENG-1899 redirect to edit entity after save and continue
  src/state/fragments/actions.js
  src/state/page-templates/actions.js
  src/state/widgets/actions.js
  test/state/fragments/actions.test.js
  test/state/widgets/actions.test.js
Labels: approved, size/S

#1012 ENG-1682 Make the page form show only groups where the user has the permission to manage pages
  src/state/groups/actions.js
  src/state/groups/const.js
  src/state/groups/reducer.js
  src/state/groups/selectors.js
  src/state/groups/types.js
  src/ui/pages/add/PagesAddFormContainer.js
  src/ui/pages/add/PagesAddPageContainer.js
  test/state/groups/actions.test.js
  test/state/groups/selectors.test.js
  test/test/mocks/groups.js
  test/test/mocks/permissions.js
  test/ui/pages/add/PagesAddFormContainer.test.js
  test/ui/pages/add/PagesAddPageContainer.test.js
Labels: approved, size/L

#1014 ENG-1883 remove join groups field for a widget
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/users/my-profile/AppSettingsForm.js
  src/ui/users/my-profile/AppSettingsFormContainer.js
  src/ui/widgets/common/WidgetFormContainer.js
Labels: approved, size/M

#1017 ENG-1510 implement better error reporting and label info for friendlyCode
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/pages/common/SeoInfo.js
Labels: approved, size/S

#1016 ENG-1461: changing image provider path
  src/helpers/microfrontends.js
  src/helpers/resourcePath.js
  src/ui/widgets/common/WidgetIcon.js
Labels: approved, size/S

#1015 ENG-1841: Adopt the new layout for the Add/Edit Widget page
  sass/index.scss
  sass/widgets/common/WidgetForm.scss
  sass/widgets/common/WidgetPage.scss
  src/ui/common/form/JsonCodeEditorRenderer.js
  src/ui/widgets/add/AddWidgetPage.js
  src/ui/widgets/common/WidgetForm.js
  src/ui/widgets/edit/EditWidgetPage.js
  test/ui/widgets/common/WidgetForm.test.js
Labels: approved, size/XL

#1018 WX-1461: fixing getResourcePath import
  src/ui/widgets/config/WidgetConfigMicrofrontend.js
  test/ui/widgets/config/WidgetConfigMicrofrontend.test.js
Labels: approved, size/XS
