Repository entando/app-builder, pull requests merged in 2021-06, with the labels that each got.

#1080 ENG-2434 selector changed with the correct one for group listing
  src/ui/groups/list/GroupListTableContainer.js
  test/ui/groups/list/GroupListTableContainer.test.js
Labels: approved, size/S

#1079 ENG-2433: setting default action on installPlan for install request
  src/state/component-repository/components/actions.js
  src/state/component-repository/components/reducer.js
  test/test/mocks/component-repository/components.js
Labels: approved, size/S

#1081 ENG-2418 Restrict username input to certain characters and force letters to be lowercase
  src/ui/common/form/RenderTextInput.js
  src/ui/users/common/UserForm.js
Labels: approved, size/M

#1082 ENG-2433: fixing instal plan readonly modal
  src/ui/component-repository/components/InstallationPlanModal.js
  test/test/mocks/component-repository/components.js
Labels: approved, size/S

#1083 ENG-2252 Improve UX of app-builder menu
  sass/internal-page/InternalPage.scss
  sass/patternfly.scss
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/ui/about/AboutInfoModal.js
  src/ui/about/AboutInfoModalContainer.js
  src/ui/internal-page/InfoMenu.js
  src/ui/internal-page/InternalPage.js
  src/ui/internal-page/VerticalMenuContainer.js
Labels: approved, size/XL

#1084 ENG-2276 fix profile type change bug
  src/ui/user-profile/common/UserProfileForm.js
  src/ui/users/list/UserSearchForm.js
  test/ui/users/list/UserSearchForm.test.js
Labels: approved, size/S

#1085 ENG-2426: always use latestVersion attribute to install a new bundle
  src/state/component-repository/components/actions.js
  src/state/component-repository/components/reducer.js
  src/ui/component-repository/components/item/install-controls/InstallButton.js
Labels: approved, size/XS

#1086 ENG-2288 Make groups alphabetically sorted in page and widget forms
  src/state/groups/actions.js
  src/state/permissions/actions.js
  src/ui/app/AppContainer.js
  src/ui/pages/add/PagesAddFormContainer.js
  src/ui/widgets/common/WidgetFormContainer.js
Labels: approved, size/S

#1087 ENG-2364 fix svg color
  sass/pages/config/WidgetGroupingListItem.scss
Labels: approved, size/XS

#1088 ENG-2275: making profile picture field to be readonly on user edit screen
  src/ui/common/form/RenderTextInput.js
  src/ui/user-profile/common/UserProfileForm.js
Labels: approved, size/XS

#1089 ENG-2451: unselecting widget when leaving edit screen
  src/ui/widgets/common/WidgetForm.js
  src/ui/widgets/edit/EditWidgetFormContainer.js
Labels: approved, size/S

#1090 ENG-2244 MFE & widgets cypress tests
  src/ui/test-const/components-test-const.js
  src/ui/test-const/page-designer-test-const.js
  src/ui/widgets/list/WidgetListTable.js
  test/cypress/integration/components-micro-frontends-and-widgets.spec.js
  test/cypress/support/command/page-designer-command.js
  test/cypress/support/command/upload-command.js
  test/cypress/support/command/widget-form-command.js
  test/cypress/support/index.js
Labels: approved, size/XL

#1091 ENG-2252 Add expand/collapse button to bottom of side nav
  sass/internal-page/InternalPage.scss
  src/helpers/useLocalStorage.js
  src/ui/internal-page/VerticalMenuContainer.js
Labels: approved, size/M

#1092 ENG-2288 Make groups sorted by name in widget and page forms
  src/ui/pages/add/PagesAddFormContainer.js
  src/ui/pages/edit/PagesEditFormContainer.js
  src/ui/widgets/clone/CloneWidgetFormContainer.js
  src/ui/widgets/common/WidgetFormContainer.js
  src/ui/widgets/edit/EditWidgetFormContainer.js
Labels: approved, size/S

#1093 ENG-2454 Add missing ecr locale message for content templates
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
Labels: approved, size/XS

#1094 ENG-2395 amended detailed validation on widget config UI field
  src/locales/en.js
  src/locales/it.js
  src/ui/widgets/common/WidgetForm.js
Labels: approved, size/M

#1095 ENG-2252 Reimplement license info as modal instead of page
  src/ui/about/AboutInfoModalContainer.js
  src/ui/internal-page/InfoMenu.js
  src/ui/internal-page/InternalPage.js
  src/ui/license/LicenseInfoModal.js
Labels: approved, size/M

#1096 ENG-2430 fix multiple tutorial running bug and management link bug
  src/state/pages/actions.js
  src/ui/app-tour/AppTour.js
  src/ui/pages/list/PageTreePageContainer.js
Labels: approved, size/XS

#1097 ENG-2464: install button to always rely on latestVersion attribute
  src/ui/component-repository/components/item/install-controls/InstallButton.js
Labels: approved, size/XS

#1098 ENG-2468 Add search functionality to template selection modal in page…
  sass/pages/common/FindTemplateModal.scss
  src/locales/en.js
  src/locales/it.js
  src/ui/common/modal/GenericModalContainer.js
  src/ui/pages/common/FindTemplateModal.js
Labels: approved, size/L
