Repository entando/app-builder, pull requests merged in 2021-05, with the labels that each got.

#1064 ENG-1828 use TextArea instead of RTE
  src/ui/widgets/common/WidgetForm.js
Labels: approved, size/XS

#1065 ENG-2371: fixing form widget clone page (also fixes ENG-2373)
  src/ui/widgets/clone/CloneWidgetPage.js
  src/ui/widgets/common/WidgetForm.js
  src/ui/widgets/config/forms/NavigationBarConfigForm.js
Labels: approved, size/L

#1066 ENG-2304 fix tutorial closing bug
  src/ui/app-tour/AppTour.js
  src/ui/app-tour/AppTourContainer.js
Labels: approved, size/XS

#1069 ENG-2393 AppBuilder: Show in the about form release number the full version
  src/helpers/versions.js
Labels: approved, size/XS

#1063 ENG-2295: removing unnecessary fetch and fixing component
  sass/pages/common/FindTemplateModal.scss
  src/ui/pages/common/FindTemplateModal.js
  src/ui/pages/common/FindTemplateModalContainer.js
Labels: approved, size/M

#1073 ENG-2288 adjust permissions url to new api endpoint
  src/api/permissions.js
Labels: approved, size/XS

#1070 ENG-2374 Make parameter fields disabled if editing a user widget
  src/ui/widgets/common/IconLibrary.js
  src/ui/widgets/common/WidgetForm.js
  src/ui/widgets/edit/EditWidgetFormContainer.js
  test/ui/widgets/edit/EditWidgetFormContainer.test.js
Labels: approved, size/S

#1071 ENG-2153: bundle distinction
  sass/component-repository/components/ComponentList.scss
  sass/component-repository/components/InstallationPlanTable.scss
  src/api/component-repository/components.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/component-repository/components/actions.js
  src/state/component-repository/components/reducer.js
  src/state/component-repository/components/selectors.js
  src/ui/component-repository/components/InstallationPlanModal.js
  src/ui/component-repository/components/InstallationPlanTable.js
  src/ui/component-repository/components/list/ComponentList.js
  src/ui/component-repository/components/list/ComponentListContainer.js
  src/ui/component-repository/components/list/ComponentListGridView.js
  src/ui/component-repository/components/list/ComponentListListView.js
  test/test/mocks/component-repository/components.js
Labels: approved, size/L

#1074 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, size/XS

#1075 ENG-2376: properly handling poll response of the new API
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/component-repository/components/actions.js
  test/test/mocks/component-repository/components.js
Labels: approved, size/M

#1072 ENG-2237 user should only see what groups he/she has access to
  package-lock.json
  src/api/groups.js
  src/state/groups/actions.js
  src/state/groups/reducer.js
  src/state/groups/selectors.js
  src/state/groups/types.js
  src/state/permissions/reducer.js
  src/state/permissions/selectors.js
  src/ui/app/AppContainer.js
  src/ui/groups/list/GroupListTableContainer.js
  src/ui/pages/add/PagesAddFormContainer.js
  src/ui/pages/config/SinglePageSettingsFormContainer.js
  src/ui/pages/edit/PagesEditFormContainer.js
  src/ui/users/common/UserAuthorityPageFormContainer.js
  src/ui/users/my-profile/AppSettingsFormContainer.js
  src/ui/widgets/clone/CloneWidgetFormContainer.js
  src/ui/widgets/common/WidgetFormContainer.js
  src/ui/widgets/edit/EditWidgetFormContainer.js
  src/ui/widgets/newUserWidget/NewUserWidgetFormContainer.js
  test/state/groups/actions.test.js
  test/state/groups/selectors.test.js
  test/test/mocks/groups.js
  test/ui/pages/add/PagesAddFormContainer.test.js
  test/ui/pages/edit/PagesEditFormContainer.test.js
Labels: approved, size/L

#1077 ENG-2153/bundle distinction fixes
  src/api/component-repository/components.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/component-repository/components/actions.js
  src/ui/component-repository/components/InstallationPlanModal.js
  test/state/component-repository/components/actions.test.js
  test/test/mocks/component-repository/components.js
Labels: approved, size/M

#1078 ENG-2394 Make MFE widget config UI required
  src/ui/widgets/clone/CloneWidgetFormContainer.js
  src/ui/widgets/common/WidgetForm.js
  src/ui/widgets/edit/EditWidgetFormContainer.js
  test/ui/widgets/edit/EditWidgetFormContainer.test.js
Labels: approved, size/M
