Repository entando/app-builder, pull requests merged in 2021-03, with the labels that each got.

#1020 ENG-1841: fix layout and icon in the upload component, changing label
  sass/widgets/common/WidgetPage.scss
  src/ui/widgets/add/AddWidgetPage.js
  src/ui/widgets/common/IconUploader.js
Labels: approved, size/XS

#1021 ENG-1906 Check for presence of free access group permissions to avoid…
  src/state/groups/actions.js
Labels: approved, size/XS

#1022 ENG-1917 adjust permissions for editUsers assignee
  src/ui/user-profile/edit/EditUserProfilePage.js
  src/ui/users/list/UserListMenuActions.js
  src/ui/users/list/UserListPage.js
Labels: approved, size/S

#1019 ENG-1796 implementation of DataTable on most tables in Appbuilder
  __mocks__/@entando/ddtable.js
  package-lock.json
  package.json
  src/index.js
  src/state/pages/const.js
  src/state/rootReducer.js
  src/state/store.js
  src/state/table-column-order/actions.js
  src/state/table-column-order/reducer.js
  src/state/table-column-order/selectors.js
  src/state/table-column-order/types.js
  src/ui/app/App.js
  src/ui/dashboard/PagesList.js
  src/ui/dashboard/PagesListContainer.js
  src/ui/fragments/list/FragmentListTable.js
  src/ui/fragments/list/FragmentListTableContainer.js
  src/ui/page-templates/list/PageTemplateListTable.js
  src/ui/page-templates/list/PageTemplateListTableContainer.js
  src/ui/pages/common/MovePageModalContainer.js
  src/ui/pages/common/PageTree.js
  src/ui/pages/common/PageTreeContainer.js
  src/ui/pages/common/dd-table/DDTable.js
  src/ui/pages/common/dd-table/DragHandle.js
  src/ui/pages/common/dd-table/TableDragLayer.js
  src/ui/pages/common/dd-table/TableRow.js
  src/ui/pages/config/frameDragSource.js
  src/ui/pages/config/frameDropTarget.js
  src/ui/pages/list/PageListSearchTable.js
  src/ui/widgets/list/ListWidgetPage.js
  src/ui/widgets/list/ListWidgetPageContainer.js
  src/ui/widgets/list/WidgetListRow.js
  src/ui/widgets/list/WidgetListTable.js
  test/state/table-column-order/actions.test.js
  test/state/table-column-order/reducer.test.js
  test/state/table-column-order/selectors.test.js
  test/test/testUtils.js
  test/ui/dashboard/PagesList.test.js
  test/ui/dashboard/PagesListContainer.test.js
  test/ui/fragments/list/FragmentListTable.test.js
  test/ui/fragments/list/FragmentListTableContainer.test.js
  test/ui/page-templates/list/PageTemplateListTable.test.js
  test/ui/page-templates/list/PageTemplateListTableContainer.test.js
  test/ui/pages/common/PageTree.test.js
  test/ui/pages/common/PageTreeContainer.test.js
  test/ui/pages/config/PageConfigPage.test.js
  test/ui/pages/config/WidgetGroupings.test.js
  test/ui/pages/list/PageListSearchTable.test.js
  test/ui/widgets/list/ListWidgetPageContainer.test.js
  test/ui/widgets/list/WidgetListRow.test.js
  test/ui/widgets/list/WidgetListTable.test.js
Labels: approved, size/XXL

#1023 ENG-1088 Implement Email Configuration feature
  package-lock.json
  package.json
  sass/email-config/EmailConfigPage.scss
  sass/email-config/EmailConfigSenderMgmt.scss
  sass/index.scss
  src/api/emailConfig.js
  src/app-init/router.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/email-config/actions.js
  src/state/email-config/reducer.js
  src/state/email-config/types.js
  src/state/rootReducer.js
  src/ui/app/App.js
  src/ui/common/form/FormSectionTitle.js
  src/ui/common/form/RenderRadioInput.js
  src/ui/email-config/AddEmailSenderFormContainer.js
  src/ui/email-config/DeleteSenderModal.js
  src/ui/email-config/DeleteSenderModalContainer.js
  src/ui/email-config/EditEmailSenderFormContainer.js
  src/ui/email-config/EmailConfigPage.js
  src/ui/email-config/EmailConfigSenderMgmt.js
  src/ui/email-config/EmailConfigSenderMgmtContainer.js
  src/ui/email-config/EmailConfigSmtpServer.js
  src/ui/email-config/EmailConfigSmtpServerContainer.js
  src/ui/email-config/EmailSenderForm.js
  src/ui/internal-page/InternalPage.js
  src/ui/internal-page/LegacyAdminConsoleMenuContainer.js
  test/api/emailConfig.test.js
  test/state/email-config/actions.test.js
  test/state/email-config/reducer.test.js
  test/test/mocks/emailConfig.js
  test/test/rtlTestUtils.js
  test/test/testUtils.js
  test/ui/email-config/AddEmailSenderFormContainer.test.js
  test/ui/email-config/DeleteSenderModalContainer.test.js
  test/ui/email-config/EditEmailSenderFormContainer.test.js
  test/ui/email-config/EmailConfigPage.test.js
  test/ui/email-config/EmailConfigSenderMgmtContainer.test.js
  test/ui/email-config/EmailConfigSmtpServerContainer.test.js
  test/ui/widgets/common/IconUploader.test.js
Labels: approved, size/XXL

#1024 ENG-1917 prevent user access edit profile
  src/ui/user-profile/edit/EditUserProfilePage.js
  src/ui/users/list/UserListMenuActions.js
Labels: approved, size/XS

#1026 ENG-1918 add MyProfile API requests
  src/api/profileTypes.js
  src/api/userProfile.js
  src/state/profile-types/actions.js
  src/state/user-profile/actions.js
  src/ui/users/my-profile/MyProfileEditFormContainer.js
  test/api/profileTypes.test.js
  test/api/userProfile.test.js
Labels: approved, size/L

#1027 Revert "Update dockerfile to patch security in default builds and to manually…"
  Dockerfile
Labels: approved, size/S

#1030 ENG-2024 Entando DataTable version bump
  package.json
Labels: approved, size/XS

#1031 ENG-2060 resolve dashboard pagelist error
  package-lock.json
  src/ui/dashboard/PagesList.js
Labels: approved, size/M

#1029 ENG-1785 add cypress commands and user management page tests
  src/ui/common/form/RenderRadioInput.js
  src/ui/common/form/RenderTextInput.js
  src/ui/common/form/SwitchRenderer.js
  src/ui/common/modal/GenericModal.js
  src/ui/test-const/test-const.js
  src/ui/test-const/user-test-const.js
  src/ui/user-profile/common/UserProfileForm.js
  src/ui/users/authority/UserAuthorityTable.js
  src/ui/users/common/AddAuthorityModal.js
  src/ui/users/common/UserAuthorityPageForm.js
  src/ui/users/common/UserForm.js
  src/ui/users/detail/DetailUserTable.js
  src/ui/users/list/UserListMenuActions.js
  src/ui/users/list/UserListPage.js
  src/ui/users/list/UserListTable.js
  src/ui/users/list/UserSearchForm.js
  test/cypress/integration/pages-management.spec.js
  test/cypress/integration/pages.spec.js
  test/cypress/integration/roles.spec.js
  test/cypress/integration/users-management-ui.spec.js
  test/cypress/integration/users-management.spec.js
  test/cypress/integration/users-roles.spec.js
  test/cypress/support/command.js
  test/cypress/support/command/command.js
  test/cypress/support/command/user-command.js
  test/cypress/support/index.js
  test/ui/users/authority/UserAuthorityTable.test.js
Labels: approved, size/XL

#1033 ENG-2069 implement roles functionality cypress testing
  src/ui/roles/common/RoleForm.js
  src/ui/roles/list/ListRolePage.js
  src/ui/roles/list/RoleListMenuActions.js
  src/ui/roles/list/RoleListTable.js
  src/ui/test-const/role-test-const.js
  test/cypress/integration/users-roles-ui.spec.js
  test/cypress/integration/users-roles.spec.js
  test/cypress/support/command/role-command.js
  test/cypress/support/index.js
Labels: approved, size/L

#1034 ENG-2009: add install plan modal to ECR
  sass/component-repository/components/InstallationPlanModal.scss
  sass/component-repository/components/InstallationPlanTable.scss
  sass/index.scss
  src/api/component-repository/components.js
  src/locales/en.js
  src/locales/it.js
  src/locales/pt.js
  src/state/component-repository/components/actions.js
  src/state/component-repository/components/reducer.js
  src/state/component-repository/components/selectors.js
  src/state/component-repository/components/types.js
  src/ui/component-repository/components/InstallationPlanModal.js
  src/ui/component-repository/components/InstallationPlanTable.js
  src/ui/component-repository/components/list/ComponentListPage.js
  test/state/component-repository/components/actions.test.js
  test/test/mocks/component-repository/components.js
Labels: approved, size/XL

#1039 ENG-2107 dont redirect to dashboard when closing app tour
  src/ui/app-tour/AppTour.js
Labels: approved, size/XS
